Dockerfile
Fixes https://github.com/jacopen/cndtattend/issues/9
ログ出力のハンドリングはここでやっている
https://github.com/jacopen/cndtattend/blob/master/config/environments/production.rb#L83
つまり、`RAILS_LOG_TO_STDOUT`の環境変数が存在すれば出力が切り替わる
=> Log to stdout

app.json
#86 の実装。
Review appsでfree版をProvisioningするように。freeは5MBしか使えないので、productionでは有料版にする。
この変更により、 `CLOUDCUBE_ACCESS_KEY_ID` `CLOUDCUBE_SECRET_ACCESS_KEY` の環境変数からcredentialをとれるので、コード側でそれを読むようにすればOK
=> Add cloudcube add-on

db/migrate/20200710134030_add_avatar_data_to_speaker.rb
元のテーブルと同じ構造が作られるようにきちんと書いた
参考：https://qiita.com/YumaInaura/items/05949d99b42516716685
=> 単純にdrop tableするだけだと、db:migrate VERSION=0でリバーとするときにエラーになる

app/views/layouts/_event_header.html.erb
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/115
https://railsguides.jp/working_with_javascript_in_rails.html#turbolinks
> Turbolinksを特定のリンクでのみ無効にしたい場合は、タグにdata-turbolinks="false"属性を追加します。
=> /:event へ遷移するときだけturbolinkを使わないことでmetaタグの更新がされずにInvalidAuthenticityTokenになる問題を解消する

app/views/layouts/_event_header.html.erb, spec/requests/profiles_spec.rb
新規登録時にリンクを押すとエラーになる状態だったので、そもそもリンクを表示させないようにした
ついでにテストも追加
=> 新規登録時にTimetableやSpeakersリンクを表示させない

app/javascript/packs/message_box.js, app/javascript/stylesheets/_message_box.scss, app/javascript/stylesheets/_timetable.scss, app/views/timetable/_timetable.html.erb
タイムテーブルの登録ボタンが分かりづらいという意見がSlackにあったので反映。
併せて #161 で指摘されている注釈を追加
=> タイムテーブルの登録ボタンを改良＆注釈追加

app/controllers/application_controller.rb, app/controllers/profiles/talks_controller.rb, spec/requests/event_spec.rb
Fix #205 
あと500エラーを別ページに飛ばす実装によってエラーの内容が確認できなくなっていたので一旦無効化
=> セッション登録後のリダイレクト先を修正

app/controllers/admin_controller.rb
スピーカーを更新したあとは `/:conference_id/speakers/:speaker_id` にリダイレクトされていたのだが、https://github.com/cloudnativedaysjp/dreamkast/pull/216 でカンファレンスの略称じゃない場合404を返すように変更したので404になっていた。
リダイレクト先を `/admin/speakers` に変更して対応します
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/226
=> スピーカーを編集したあと404になる問題を修正

app/views/talks/show.html.erb
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/227
=> talkページをtwitterにシェアする際、ハッシュタグの `#` が重複している問題を修正

app/javascript/packs/message_box.js
* https://event.cloudnativedays.jp/cndt2020/timetables のURLへアクセスした際に以下のスクリプトエラーが発生します。
* PCのGoogle ChromeブラウザとiPhoneのSafariブラウザにて事象を確認しました。
```
message_box.js:8 Uncaught TypeError: t(...).touchmove is not a function
at HTMLDocument.<anonymous> (message_box.js:8)
at c (jquery.js:3235)
at f (jquery.js:3277)
```
* jQueryオブジェクトにはtouchmoveというメソッドがないため、未定義エラーとなります。そのため、jQueryオブジェクトのbindメソッドを利用してイベントリスナを登録するように修正しました。
* また、PCのブラウザではtouchmoveイベントが動作しないため、代替のmousemoveイベントにて同じ処理のイベントリスナを登録するように修正しました。
* https://cndt-dreamka-fix-script-l8it3h.herokuapp.com/cndt2020/registration のURLへアクセスした際に以下の動作となることを確認しました。
* スクリプトエラーが発生しないこと（PCのGoogle Chromeブラウザ・iPhoneのSafariブラウザ）。
* ブラウザのウィンドウの任意の場所へマウスオーバした際に「聞きたいセッションを登録しましょう。セッション名をクリックすると詳細が表示されます。」のメッセージが非表示になること（PCのGoogle Chromeブラウザ）。
* …
=> サイト表示時にスクリプトエラーが発生する事象を修正しました。

db/fixtures/development/seeds.rb
talks_speakers.csvにidカラムがないため、db:seedを実行する毎にtalks_speakersレコードが追加されてしまっていた。talk_idとspeaker_idを識別子として扱うようにします。
=> db:seedを実行する毎にtalks_speakersが増える問題を修正

app/javascript/packs/tracks/track_control.js
#248 
- ページを開いて動画再生されるのと同じタイミングでタイマー(setInterval)をセット
- 2分後にKarteへのデータ送信。その後も2分おきに送信される(視聴時間を大まかに把握できるようにするため)
- 2分のIntervalがあるので、単純にトラックをザッピングしただけではデータは送信されない
動作確認するにはKarteの管理者権限が必要(自分と青山さんしかアクセスできない)
以下は実際に確認してみたログ。
- 初回送信。データにトラックA,ID1が入っているのが分かる(7番ログ)
- ちょうど2分後に再度送信(6番、5番)
- トラックCに移動。移動してから2分後にログ送信。トラックC、ID3(4番、3番)
- クライアントはそのままに、管理画面から放送を差し替え。トラックCのままID10になっていることが分かる(2番、1番)
=> Implement karte logging to track page

app/helpers/application_helper.rb
child_indexが未指定のため、複数個ファイルを添付しようとすると同じindex(0)となり片方の添付に失敗していた
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/256
=> ブーススポンサーのキーイメージとPDFを複数個同時に添付しようとすると失敗する問題を修正

app/controllers/dashboard_controller.rb, app/controllers/tracks_controller.rb, app/javascript/stylesheets/_global.scss, app/views/dashboard/_booth_section.html.erb, app/views/dashboard/show.html.erb, app/views/layouts/_event_header.html.erb, app/views/tracks/index.html.erb
- ダッシュボードにブースリストを表示
- トラックページにブースリストを表示
- 上記2つのリストはシャッフルして表示
- ヘッダー上の表示位置を左端に変更
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/262
=> ブース一覧をダッシュボードとトラックページに表示

app/controllers/event_controller.rb, app/controllers/tracks_controller.rb, spec/controllers/tracks_controller_spec.rb, spec/factories/conferences.rb, spec/requests/tracks_spec.rb
ConferenceがOpenedになったらtracksをデフォルトのリダイレクト先として指定するようにした
また、今回の修正で併せてtracksをログイン要にした
- tracksページとdashboardページの導線を見直す必要あり
- Navbarも併せて見直しかなぁ
=> dashboardとtracksをスイッチ可能に

app/controllers/auth0_controller.rb, app/views/event/show.html.erb
結構頻繁に起きてるこのエラー
https://sentry.io/organizations/cloudnative-days/issues/1810758959/?project=5350644&query=is%3Aunresolved#exception
https://github.com/cloudnativedaysjp/dreamkast/blob/master/app/middlewares/rescue_from_invalid_authenticity_token.rb#L9-L11
でInvalidAuthenticityTokenが起きたときはリダイレクトするようにしてるんだけど、エラーの内容を読む限りここに引っかかるのではなく、Auth0 Controllerのfailureが呼ばれているケースがある様子。
https://github.com/cloudnativedaysjp/dreamkast/blob/master/app/controllers/auth0_controller.rb#L17-L20
ただ、このactionに対するテンプレートが無いため上記エラーが発生しているものと推測。
対策としてはfailureにview templateを用意するか、リダイレクトするか。
InvalidAuthenticityTokenでもリダイレクトしているので、今回もそのままリダイレクトする形にした。
ログインパスが相対パスになっていて、これが原因でエラーがあるようだった(slack参照)　ので修正した
=> Fix MissingExactTemplate when CSRF detected

Gemfile, Gemfile.lock, README.md, config/database.yml, config/puma.rb
- rack-timeoutを入れてタイムアウト時間を設定できるように
- pumaのworkersを環境変数で可変に
これにより以下の4環境変数でチューニングを行う
WEB_CONCURRENCY - pumaのworker(プロセス数)を設定
RAILS_MAX_THREADS - pumaの最大スレッド数を設定
RAILS_MIN_THREADS - pumaの最小スレッド数を設定
RACK_TIMEOUT_SERVICE_TIMEOUT - pumaのタイムアウト時間を設定
いずれもHeroku公式に紹介されている設定。
https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server
=> パフォーマンスチューニング

app/javascript/packs/booth.js, app/views/booths/_booth.html.erb
#248 
boothに訪問するとkarteに情報がいくようにした
以下karteでの動作確認ログ
=> Add booth tracking

app/controllers/application_controller.rb, app/controllers/concerns/secured.rb, spec/requests/contents_spec.rb, spec/requests/event_spec.rb, spec/requests/talks_spec.rb, spec/requests/timetable_spec.rb
Auth0でログインしたがプロフィール入力をしていないユーザーがtimetableやtalksページを見ると500エラーになっていたので、強制的にリダイレクトするように
Fix #291
=> ログインしているが未登録ユーザーは登録画面にリダイレクト

config/initializers/session_store.rb
=> redisに保存するセッションの有効期間が短い

app/javascript/packs/application.js, app/javascript/packs/contents.js, app/views/contents/index.html.erb, app/views/layouts/_event_header.html.erb
* Kontest / Discussion Board / Kubernetes Upstream Training への導線をわかりやすく
* read moreを追加して、画面上にコンテンツが複数見えやすいようにする（Discussion Boardに気づかないかもしれないので）
* /cndt2020/contents#kontest で飛べるようにした
=> Improving other contents

lib/tasks/relate_profile_to_cndt2020_if_conference_id_is_nil.rake
https://github.com/cloudnativedaysjp/dreamkast/pull/345 で各モデルにconference_idを追加していて、Profileだけは更新オペレーションが必要なのでRakeタスクを書いた（他のモデルはseedで追加した）。
https://github.com/cloudnativedaysjp/dreamkast/issues/348
=> add rake task: update profiles that don't have conference_id

app/views/layouts/_event_header.html.erb
ヘッダ画像へのパスが間違っていてCNDT2020のロゴが見えなくなってしまっていた問題を修正
ref: https://github.com/cloudnativedaysjp/dreamkast/pull/345
=> fix header image path

app/controllers/speaker_dashboard/speakers_controller.rb
Speaker検索にConference情報が使われていなかったため、複数のカンファレンスでスピーカーになっている場合Forbiddenになることがある。
=> 複数のカンファレンスでSpeakerになっている際にForbiddenになることがある問題を修正

app/models/talk.rb
フロントサイドではrequiredがついていないのだけど、Rails側でバリデーションしていて空欄のままだとうまく登録できなくなっていた。
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/385
=> エントリーフォームの「セッション概要」は空欄のまま申し込んでもよい

app/controllers/admin/conferences_controller.rb, app/controllers/event_controller.rb, app/forms/conference_form.rb, app/javascript/stylesheets/cndo2021/_cndo2021.scss, app/models/conference.rb, app/views/admin/conferences/_form.html.erb, app/views/event/cndo2021_show.html.erb, app/views/event/partial/_about.html.erb, app/views/event/partial/_attendee_entry_button.html.erb, app/views/event/partial/_buttons.html.erb, app/views/event/partial/_information.html.erb, app/views/event/partial/_speaker_entry_button.html.erb, app/views/event/partial/_sponsors.html.erb, app/views/event/show.html.erb, db/fixtures/development/seeds.rb, db/fixtures/production/seeds.rb, db/migrate/20210113131031_add_speaker_entry_and_attendee_entry_columns_to_conference.rb, db/schema.rb, spec/factories/conferences.rb
https://github.com/cloudnativedaysjp/dreamkast/issues/349
Conferenceにspeaker_entryとattendee_entryを追加
speaker_entryとattendee_entryの値に応じてスピーカーと参加者向けエントリーボタンの表示を制御するようにした
adminページからspeaker_entryとattendee_entryを変更可能にした
=> スピーカー/参加者のエントリーボタンの表示を制御可能にする

app/views/speaker_dashboards/show.html.erb
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/390
=> スピーカーダッシュボード上でセッション概要を表示する際、改行を反映する

app/views/admin/booths/index.html.erb, app/views/admin/sponsors/index.html.erb
adminページは各イベントの配下に移動してURLが変わったのだった。
=> admin用ページでブースやスポンサーが見えない問題を修正

app/controllers/admin/talks_controller.rb, app/models/talk.rb, app/views/admin/talks/index.html.erb, app/views/talks/index.html.erb
- トーク一覧画面に希望セッション時間を追加
- admin画面からCSVでトーク一覧をダウンロードできるようにした
https://github.com/cloudnativedaysjp/dreamkast/issues/415
=> 希望セッション時間を見えるようにする

app/views/event/partial/_speaker_entry_button.html.erb, app/views/speaker_dashboard/speakers/_form.html.erb, app/views/speaker_dashboard/speakers/_talk_fields.html.erb
speaker_entry_disableの時、
- エントリー済みの人にはスピーカーダッシュボードへのリンクを表示
- エントリー済みの人がトークの追加・削除ができないように変更（更新は可能）
- 未エントリーの人にエントリーボタンを表示しないようにする
=> エントリー受付終了時の挙動変更

app/views/talks/_show_modal.html.erb
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/481
=> タイムテーブルでトーク詳細を見た時、スピーカーのプロフィールが改行されていない問題を修正

app/views/talks/_show_modal.html.erb
Related #481 
Modalのトーク概要欄も改行反映されていなかったので直した
=> Fix modal page

app/views/admin/talks/index.html.erb
- URL生成のメソッド名が間違っていた
- そもそもリンクにすらなっていなかった（ひどい）
https://github.com/cloudnativedaysjp/dreamkast/issues/491
=> トーク一覧の表示エラーを修正

.github/workflows/gitops-dev.yml, .github/workflows/gitops-prd.yml
* cloudnativedaysjp/dreamkast-infra 以下の特定ファイルを置換するルールの追加 : `s/ENVIRONMENT/production/g` または `s/ENVIRONMENT/development/g`
* dreamkast を展開する argo-cd Application の `.spec.source.path` にこの変数が必要なため
* cloudnativedaysjp/dreamkast-infra では以下で対応済みなため、 **当 PR を merge しないと新しく生えた PR での preview-app のデプロイが失敗することに注意**
* https://github.com/cloudnativedaysjp/dreamkast-infra/commit/de4a1bb2833a5a4ba003646b90af5c74f61577fc
* cloudnativedaysjp/dreamkast-ui と共通化可能な GitOps 周りの処理を GitHub Action として以下のリポジトリに切り出しました
* https://github.com/cloudnativedaysjp/action-dreamkast-gitops
=> fix GitHub Action for GitOps

app/models/talk.rb, app/views/api/v1/talks/index.json.jbuilder, app/views/api/v1/talks/show.json.jbuilder, schemas/swagger.yml
ついでにconferene_dayが空の場合にエラーにならないように修正
https://github.com/cloudnativedaysjp/dreamkast-api-docs/pull/16
=> speakersは名前の配列を返す

.github/workflows/gitops-stg.yml
- main merge 時に staging, tagged 時に production が release されるよう GitHub Actions を修正
- 以下の PR を先に merge
- cloudnativedaysjp/dreamkast-infra#11
=> separate prd & stg in gitops Action

app/channels/on_air_channel.rb, app/controllers/admin/talks_controller.rb, app/helpers/talks_helper.rb, app/javascript/channels/consumer.js, app/javascript/channels/index.js, app/javascript/channels/on_air_channel.js, app/models/talk.rb, app/models/video.rb, spec/channels/on_air_channel_spec.rb
admin画面でtalkのオンエアを切り替えた際、`"on_air_#{params["eventAbbr"]}"` チャンネルに通知します。
通知内容は各トラックでオンエアしているトークの一覧（トラックIDとトークのマップ）
https://github.com/cloudnativedaysjp/dreamkast-ui/pull/56
=> オンエアの自動切り替え v2

app/controllers/api/v1/talks_controller.rb, app/views/api/v1/talks/index.json.jbuilder, app/views/api/v1/talks/show.json.jbuilder, schemas/swagger.yml
後でAPI定義とそろえる
- 1,2のように複数指定できるようにしている
API: https://github.com/cloudnativedaysjp/dreamkast-api-docs/pull/19
=> conference_dayでtalk一覧を検索するためのパラメータを追加

.github/workflows/gc.yaml, .github/workflows/gitops-dev.yml, .github/workflows/gitops-prd.yml, .github/workflows/gitops-stg.yml
* 従来: dreamkast-infra に対して push to main
* これ以降 : push to temporary branch && create PR && merge PR
これにより、複数 GitHub Actions が同時に走ることによる push Error を回避する
* merge 前に https://github.com/cloudnativedaysjp/dreamkast-infra にて[ブランチの自動削除機能](https://docs.github.com/ja/github/administering-a-repository/managing-the-automatic-deletion-of-branches) を有効化してもらいたいです
* これがないと、 2 回目以降の push 時に GitHub Actions が dreamkast-infra に対して同名 branch を push しようとしてエラーする
=> dreamkast-infra の資材更新方法変更

app/controllers/speaker_dashboard/videos_controller.rb
非同期化するのがベストだが、今回はログ出力するのみにとどめます
https://github.com/cloudnativedaysjp/dreamkast/issues/531
=> メール送信時に例外が発生した場合はエラーログを出力するだけにとどめる

.github/workflows/gc.yaml, .github/workflows/gitops-dev.yml, .github/workflows/release.yml
- `release/{major,minor,patch}` label を付けて PR を merge すると、自動で現在の latest tag から {major,minor,patch} をインクリした tag を push する GitHub Action を追加
- `release/{major,minor,patch}` label を付けた際に gitops-dev , gc GitHub Action が動作しないようにした
- https://github.com/cloudnativedaysjp/dreamkast-ui/pull/98
=> 自動で新バージョンの tag を付与する GitHub Actions を追加

.github/workflows/release.yml
* git tag を push するのに https://github.com/showks-containerdaysjp のトークンを利用するようにした
* Action の push 契機では Actions が走らないという仕様に対応
* 参考: https://www.yslibrary.net/2020/04/18/actions-checkout-v2-push/
=> modify GitHub Actions

app/models/talk.rb, app/views/talks/partial_show/_talk_video_block.html.erb, spec/requests/talks_spec.rb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/618
=> セッションパーマリンク側もライブが終わるまでは非公開にする

app/views/event/partial/_speaker_entry_button.html.erb, app/views/layouts/_event_header.html.erb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/619
以下の場合、スピーカーダッシュボードへのリンクをイベントトップページと右上メニューに表示する
- カンファレンス開催前、かつスピーカーエントリー受付中
- カンファレンス開催中、かつ自身がスピーカーの場合
- カンファレンス開催後、かつ自身がスピーカーの場合（開催後に資料URLを追加することを想定）
=> カンファレンス開催中、開催後もスピーカーはスピーカーダッシュボードを見られるようにする

Dockerfile, Gemfile.lock, README.md
mimemagicをバージョンアップするか、mimemagicパッケージを削除するかの二つの方法があるが今回は前者を選択する。
dreamkastが現在使っている `rails_autolink` パッケージがmimemagicパッケージをインストールしてしまう (たぶん使ってないんだけど、railsに依存していてインストールされる）ため。
https://hackmd.io/@mametter/mimemagic-info-ja
=> Upgrade mimemagic

db/fixtures/production/seeds.rb
シード値にStatusを含めていると手動でシード値と異なる値にStatusを変更した後にデプロイが走るとシード値のStatusに上書きされてしまう。
=> remove status seed

app/views/speaker_dashboard/speakers/_talk_fields.html.erb, app/views/speaker_dashboards/show.html.erb, spec/factories/conferences.rb, spec/requests/speaker_dashboard_spec.rb
=> CFP受付中はビデオの投稿や資料URLを非表示に

config/database.yml
https://github.com/cloudopsdays/dreamkast/pull/48 のバックポート
=> yamlの値に記号が入っても文字列で評価されるようダブルクォーテーションで囲った

app/controllers/speaker_dashboard/speakers_controller.rb, app/mailers/speaker_mailer.rb, app/models/talk.rb, app/views/speaker_mailer/cfp_registered.text.erb
#701  
- create からは無条件にメール送信
- update の際は talk_id を保存して save の結果と比較することで create を判定
- メール文面
- 本番環境の SES 動きますよねという確認(@takaishi さんのメールが認証されているだけだったので動くのか気になりました)
- エスケープしてないので改行が入ると文面が崩れますけど、対応が必要かどうか
=> CFP の新規作成時にメール送信する

app/controllers/admin/conferences_controller.rb, app/controllers/admin/proposals_controller.rb, app/controllers/speaker_dashboards_controller.rb, app/forms/conference_form.rb, app/forms/speaker_form.rb, app/models/conference.rb, app/models/proposal.rb, app/models/proposals_speaker.rb, app/models/speaker.rb, app/models/talk.rb, app/views/admin/_navigator.html.erb, app/views/admin/conferences/_form.html.erb, app/views/admin/proposals/index.html.erb, app/views/admin/show.html.erb, app/views/speaker_dashboards/show.html.erb, config/routes.rb, db/migrate/20210216095643_update_columns_to_chat_messages.rb, db/migrate/20210607093009_create_proposals.rb, db/schema.rb, lib/tasks/create_proposals_of_cicd2021.rake, spec/factories/conferences.rb, spec/factories/proposals.rb, spec/factories/speakers.rb, spec/requests/speaker_dashboard_spec.rb
https://github.com/cloudnativedaysjp/dreamkast-kanban/issues/32
* Proposalsテーブルを追加。Statusカラムでプロポーザルの採択・非採択をコントロールする
* Conferenceテーブルにプロポーザルの採択結果を公開するかどうかのフラグを追加。proposalsで採択・非採択しても、こちらで公開しないとスピーカーからは見えない。
* CICD2021の既存の各TalkにProposalを追加するためのRakeタスクを追加。このPRをデプロイ後に手動でタスクを実行する。デプロイ後に追加されるTalkには自動的にProposalは作られる。
=> Support cfp accepting

app/views/talks/partial_show/_col_talk_category_block.html.erb, app/views/timetable/_talk_category_difficulty.html.erb
スポンサーセッションの場合、それとわかるようにラベルを表示する。追加するのは以下。
- タイムテーブル
- セッションページ
https://github.com/cloudnativedaysjp/dreamkast/issues/713
=> スポンサーセッションかどうかわかるようにする

app/controllers/admin/talks_controller.rb, app/controllers/admin/timetables_controller.rb, app/models/talk.rb, app/views/timetable/_timetable.html.erb
- `/admin/timetables` にはacceptedなセッションのみ表示する
- `/admin/talks` にはacceptedなセッションのみ表示する
- `/admin/timetables` において、セッションの時間の取得方法を更新
- CICD2021はProposalでセッション時間を取得しておらず、40min固定なのでそれを返すようにする
- CNDT2021以降はセッション時間はProposalItemを使って管理しているので、ProposalItemに`session_time` のラベルを持つものがあれば使うようにする
=> admin画面細々修正

app/controllers/sponsor_dashboards/speakers_controller.rb, lib/tasks/fix_proposal_items_for_cicd2021.rake
- スポンサーダッシュボードからセッションを登録する際、一部の項目が保存されない問題を修正
- CNDT2021のCFPオープンのため、ProposalItemを導入してカンファレンス毎にCFPの項目を動的に変更できるようにした。しかし、スポンサーセッションを登録するためのコントローラーを修正できていなかった。
- ProposalItem導入時にtalksテーブルの `expected_participants` と `execution_phases` をProposalItemにマイグレーションした。PropsalItemのparamに入るのはProposalItemConfigのidの配列でなければならないのだが、0が混ざっていてエラーになっていた。マイグレーション時に消さないといけなかったが考慮が漏れていた。
=> CICD2021向け修正

app/controllers/admin/tracks_controller.rb, app/helpers/talks_helper.rb, app/views/admin/talks/index.html.erb, app/views/admin/tracks/_tracks_nav.html.erb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/798
- admin/tracksからtrackのvideo_idを設定可能にした
- video_idが設定されているとき、admin/tracksにvimeoへのリンクを表示するようにした
- sli.doはもう使っていないのでadmin/tracksとadmin/talksのフォームから削除した（過去イベントにはsli.doの情報が残っているのでDBからはまだ消さない）
=> add form for video_id of Track

app/views/event/cicd2021_show.html.erb
profileがないとtalks_checked?がエラーになる。
c.f. https://github.com/cloudnativedaysjp/dreamkast/pull/804
=> ログインしてプロフィールを入力する前にイベントページ見るとエラーになる問題を修正

app/channels/track_channel.rb, app/channels/waiting_channel.rb, app/controllers/admin_controller.rb, app/controllers/tracks_controller.rb, app/helpers/talks_helper.rb, app/models/announcement.rb, app/models/booth.rb, app/models/video.rb, app/views/event/cicd2021_show.html.erb
- Video.on_airが全video見ていたのをカンファレンスを渡してその下のものだけに変更
- 関連して使っていないであろうActionCableのupdateメソッドを削除
- tracks_controllerで全リソース取得していたのでカンファレンスに関連するものだけ取得するように変更
=> カンファレンスのスコープでリソースを取得していない箇所を修正

app/jobs/chat_message_broadcast_job.rb
action cableで送っているチャットメッセージにcreated_atが含まれておらず、レンダリング時に投稿時間がおかしくなっていた。
APIのレスポンスには含まれているため( https://github.com/cloudnativedaysjp/dreamkast/blob/main/app/views/api/v1/chat_messages/index.json.jbuilder#L9 )、リロードすると正しく表示される。
fix https://github.com/cloudnativedaysjp/dreamkast-ui/issues/156
=> チャットの投稿時間がおかしくなる問題を修正

app/controllers/sponsor_dashboards/sponsor_profiles_controller.rb
スポンサーのスピーカーリストに記入されたメールアドレスに大文字が混ざっている場合、小文字にして比較しないと異なるアドレスと判定することがある。しかし、一般的には大文字・小文字は区別しないので小文字に変換して比較する。
=> メールアドレスの比較時に大文字・小文字を区別しないようにする

app/models/conference.rb, lib/tasks/post_number_of_registrants_to_slack.rake
- registered, open, closedのカンファレンスについて全て通知する用に変更
- 前日のstatsを取得する際にカンファレンスIDを含めて取得するように変更
=> improve notifying number of registrants

app/controllers/admin/teams_controller.rb, app/controllers/teams_controller.rb, app/javascript/stylesheets/_team.scss, app/javascript/stylesheets/application.scss, app/javascript/stylesheets/cndt2021.scss, app/models/admin_profile.rb, app/models/conference.rb, app/views/admin/_navigator.html.erb, app/views/admin/teams/show.html.erb, app/views/layouts/_event_header.html.erb, app/views/teams/show.html.erb, config/routes.rb, db/migrate/20210923023142_add_show_on_teams_page_columns_to_admin_profile.rb, db/schema.rb
- `cndt2021/team` にメンバー情報を表示できるようにする
- 今回はメンバーのロールは考慮せず、名前順で表示
- 表示するのは AdminProfileの `name` と `twitter_id` 、 `github_id` 、 `avator`
- adminとして管理者ページにログインして `cndt2021/admin/admin_profiles/1/edit` から管理者プロフィールを登録するする必要がある
- 表示するかどうかを AdminProfile の `show_on_team_page` で制御する ( `cndt2021/admin/team` から編集 )
fix https://github.com/cloudnativedaysjp/dreamkast/issues/745
=> Add team page

docker-compose.yaml
Docker composeでmail-workerを立ち上げられるように。
利用する際には.envに `SQS_MAIL_QUEUE_URL=https://sqs.ap-northeast-1.amazonaws.com/607167088920/devMailQueue.fifo` (あるいは利用したSQS URL)を追記して利用する
=> Add mail-worker

app/controllers/teams_controller.rb
ログインした状態で Team ページにアクセスするとユーザアイコンが表示されず、代わりにログインボタンが有効化されている
view に `@current_user` が渡されていなかった
Controller で Secured を include した  
非ログイン状態でも見れる方が良いと思ったので `logged_in_using_amniauth?` メソッドをリダイレクトしないようにオーバーライドした
=> Team ページで認証されてないように見える不具合の修正

app/controllers/talks_controller.rb, app/views/admin/talks/index.html.erb
- CFPの結果をオープンにした際、Talkがconference_day_idを持っていないと /talks に表示されない問題を修正
- admin/talks を開いた際、 Talkがconference_day_idを持っていないとエラーになる問題を修正
fix https://github.com/cloudnativedaysjp/dreamkast/issues/878
=> セッション一覧の表示周り修正

app/controllers/admin/tracks_controller.rb, app/models/talk.rb, app/views/admin/tracks/_tracks_nav_cndt2021.html.erb
Fix #952
TracksページにCSV出力機能を実装した。
出力ファイル名: `<イベント名>_<日付>_<トラック名>.csv`  例: `cndt2021_2021-11-04_A.csv`
出力カラム: Talksページで出るものと同一 `id,title,abstract,speaker,session_time,difficulty,category,created_at,twitter_id,company,start_to_end,assumed_visitor,execution_phase,whether_it_can_be_published,language`
注意点:
- セッションのStartとEndの情報が欲しいという要望があったので、 `start_to_end` を増設している。
- Talksと同じメソッドにパラメータを付与する形で実装したため、Talks側で出せるCSVにも↑が反映されている。よってカラムのズレが発生しているので注意
- Talks側で出せるCSVのファイル名が `cndt2021_all_all.csv` に変更になっている
=> Improve csv exporter

.github/workflows/ci.yaml
CIのジョブの名前が「Build deploy」ってなってるけど実際にはテスト動かしてるだけなのでややこしいと思って直した
=> Modify CI job name

app/controllers/application_controller.rb, spec/requests/application_spec.rb
`https://event.cloudnativedays.jp/data/admin/allowurl.txt` のような、拡張子がtxtのURLの場合表示するテンプレートもtxtのものを探そうとして存在しないので500エラーとなっている。
拡張子がなんであれ、htmlのテンプレートを使うようにして500エラーにならないようにしたい。
=> html以外のURLが404の時にもhtmlのerrorファイルを表示する

config/initializers/sentry.rb
SentryのエラーにNamespaceの情報を付与する
メールでもSlack通知でもどこの環境で発生してるのかすぐわかるので便利になる
=> Add context

app/models/conference.rb
closes #1010
期待する挙動は実現できましたが、scopeで`ActiveRecord::Relation`ではなく`Array`を返すようにする是非が気になっています。
> 4-1. ActiveRecord::Relation を返すように義務付ける
個人的には scope って ActiveRecord::Relation を返す目的で使うものだと思っていたのですが、
以下のように Array など別のクラスを返す scope がよくあります。
> 
> scope :latest_users, -> { order(created_at: :desc).first(5) }
これだと scope メソッド同士での連結ができませんし、
一度 Array になってしまうと使い道にも制限が出てしまうので、あまり良くないと思います。
https://nekonenene.hatenablog.com/entry/do-not-use-rails-scope
今のところ1箇所でしか使われていませんが、どうなんでしょう。
```
git grep previous 
app/controllers/home_controller.rb:    @previous = Conference.previous
app/javascript/packs/bootstrap-table.js:              var previousLastIndex = rx.lastIndex;
app/javascript/packs/bootstrap-table.js:              if (!sameValue(previousLastIndex, 0)) rx.lastIndex = 0; …
```
=> sort archives by conference id

schemas/swagger.yml, spec/requests/api/v1/chat_message_index_spec.rb
https://github.com/cloudnativedaysjp/dreamkast/issues/1011
- swagger
- `GET /api/v1/chat_messages` のレスポンスボディはChatMessage Objectの配列なので、swaggerでも配列を明示する必要があった
- requiedの `talkId` は間違いで `roomId` が正しい
- `speakerId` と `replyTo` にはnullが入る可能性があるのでnullableにする
api-doc: https://github.com/cloudnativedaysjp/dreamkast/pull/1012
=> add test: GET /api/v1/chat_messages

app/helpers/env_helper.rb, app/models/live_stream_ivs.rb, app/models/live_stream_media_live.rb
IVSとMediaLiveのリソース名にPRの番号をつけ、タグにもPR番号をつけるようにした。PRクローズ時にタグ情報を元にリソースを削除する機能を別途実装予定。
fix https://github.com/cloudnativedaysjp/dreamkast/issues/1034
=> use PR number for IVS/MediaLive resource name

.rubocop.yml, config/aws_sqs_active_job.yml, lib/tasks/aws_sqs.rake, lib/tasks/dev_sqs.rake
SQS のメッセージを複数のワーカーで食い合う問題を修正。
`DREAMKAST_NAMESPACE` を使ってSQSにキューを作成/削除する Rake task を作成。
同時に Polling 時にキューのURLを動的に生成する必要があったため worker のコマンドを変更する必要がありました。
P/Rの作成/削除の際の Task トリガーについては別途実装予定です(infra との兼ね合いでタイミングは考えます)。
`queue_url` メソッドが呼ばれるたびに AWS::Client の初期化が走るのがあんまり良くないポイントとして残ってしまったので良い解決法があれば教えて欲しいです。
この実装にしているのは AWS の AccountId とかをハードコーディングしたくないなーというのが背景にあります。
=> review_app で使用するキューをDkから作成できるようにする

app/controllers/talks_controller.rb, app/models/proposal_item.rb, app/models/proposal_item_config.rb, app/models/proposal_item_config_check_box.rb, app/models/proposal_item_config_radio_button.rb, app/models/talk_category.rb, app/models/talk_difficulty.rb, app/views/talks/partial_show/_col_main_pane.html.erb, app/views/talks/partial_show/_talk_video_block.html.erb, app/views/talks/partial_show/_talk_video_block_videojs.html.erb, config/initializers/constrants.rb, db/fixtures/development/01_proposal_item_configs.rb, db/fixtures/production/01_proposal_item_configs.rb, db/migrate/20211211104841_add_columns_to_proposal_item_config_and_change_type.rb, db/schema.rb, spec/controllers/talks_controller_spec.rb, spec/factories/proposal_item.rb, spec/factories/proposal_item_configs.rb, spec/factories/talks.rb
https://github.com/cloudnativedaysjp/dreamkast/issues/1022
このPRではProposalItemを使ったアーカイブ動画の表示制御とテストの追加を行う。また、そのためにProposlItemConfigの項目を識別するために新しくkeyとvalueのカラムを追加する。keyはプログラムから識別するためのunique idを、valueはユーザーに表示するテキストを保持する。valueとparamsに同じ値が入っているが、これはparamsを今後消すためである(paramsがvaluesに置き換わる)
動画の公開可否は ProposalItemで制御するパターンと video_publlished で制御するパターンの2種類がある。前者はCNDT2021以降で使われる。後者は基本的に今後は使わない。
まず、カンファレンスのステータスとログインしているかどうかで動画を表示するかを制御する。以下のいずれかの条件を満たす場合、2もしくは3の条件チェックに進む。
- カンファレンスがクローズ状態、かつ閲覧者が参加者としてログインしている
- カンファレンスがオープン状態、かつ閲覧者が参加者としてログインしている
- カンファレンスがアーカイブ状態
ProposalItemに紐付いている(paramsにidが含まれている)ProposalItemConfigのkeyが `ALL_OK`, `ONLY_SLIDE`, `ONLY_VIDEO`, `ALL_NG`, `OTHERS` のうち `ALL_OK` もしくは `ONLY_VIDEO` の場合は表示する
以下を全て満たしている場合は表示する。
- talk.video_published : talkレコードのvideo_publishedカラムがtrue
- …
=> アーカイブ動画の表示・非表示まわりの修正

app/helpers/media_live_helper.rb, lib/tasks/aws.rake
以下のリソースについて、`Environment` タグの値が `review_app` のもの、かつ `ReviewAppNumber` タグの値が `DREAMKAST_NAMESPACE` 環境変数で指定されたPR番号のものを消す
- IVS Channel
- MediaLive Input
- MediaLive Channel
=> ReviewApp用に作成されたAWSのリソースを削除するためのRakeタスクを追加

app/controllers/speaker_dashboard/speakers_controller.rb
SSIA
https://github.com/cloudnativedaysjp/dreamkast/blob/main/app/controllers/speaker_dashboard/speakers_controller.rb#L44　で未初期化のインスタンス変数 `@speaker` を渡しているため worker で `NoMethodError (undefined method `email' for nil:NilClass)` が起こっている.
Update では発生しないのと、#1060 の不具合が先に発生するため顕在化しなかったと考えられる
save 成功後に `@speaker` に `@speaker_form.email` で照合した Speaker を代入した
=> スピーカー作成と同時にCFPを作成するとメールが送信できない不具合の修正

app/forms/speaker_form.rb, app/models/talk.rb, app/views/speaker_dashboard/speakers/_talk_fields.html.erb
CFP 登録時にチェックボックス及びラジオボックスの選択肢が必須のはずが、選択無しでも validation をパスしてしまっている
#1068 
以下の validation では `expected_participants` と `execution_phases ` が常に `nil` のため、機能しない
https://github.com/cloudnativedaysjp/dreamkast/blob/6740edf41978fd6743d74544cb5d0609bde43f0f/app/models/talk.rb#L63-L64
https://github.com/cloudnativedaysjp/dreamkast/blob/6740edf41978fd6743d74544cb5d0609bde43f0f/app/models/talk.rb#L303
validation を `talk.proposal_items` と `conference.proposal_item_configs` のサイズの比較で行うように変更した
現状全て必須項目のため必ず両者のサイズが一致し、もし差ができた場合はその差を不足分としてエラー表示に出している
rspec 実施時、下記の `proposal_items` が実行されると `spec/controllers/talks_controller/display_document_spec.rb` で `true` を期待値とする spec が全滅したため context を設定して factory からの save 時に validation を無効化しました。
https://github.com/cloudnativedaysjp/dreamkast/blob/cf317e308e7f241f73240b …
=> 必須項目を選択しなくてもセッション情報を登録できてしまう不具合の修正

app/models/live_stream_ivs.rb, app/models/live_stream_media_live.rb
https://github.com/cloudnativedaysjp/dreamkast/pull/1035 でReviewAppNumberタグをAWSリソースに追加するようにしたが、DREAMKAST_NAMESPACEがないときも追加しようとしてエラーになることがあったので環境値変数をチェックするようにします
=> ReviewAppNumberタグをセットするのはDREAMKAST_NAMESPACE環境変数がセットされているときだけ

app/models/talk.rb, db/migrate/20220118092940_add_index_talks_conference_id.rb, db/schema.rb, spec/factories/talks.rb
スロークエリのログ
```sql
SELECT t.id,t.title,td.name AS talk_difficulty FROM talks t LEFT JOIN talk_difficulties td ON t.talk_difficulty_id = td.id WHERE t.conference_id='5'\G
```
Before:
```
mysql> EXPLAIN SELECT t.id,t.title,td.name AS talk_difficulty FROM talks t LEFT JOIN talk_difficulties td ON t.talk_difficulty_id = td.id WHERE t.conference_id='5';
+----+-------------+-------+------------+--------+---------------+---------+---------+--------------------------------+------+----------+-------------+
| id | select_type | table | partitions | type   | possible_keys | key     | key_len | ref                            | rows | filtered | Extra       |
+----+-------------+-------+------------+--------+---------------+---------+---------+--------------------------------+------+----------+---------- …
```
=> Add index on talks table

app/models/media_package_channel.rb, db/migrate/20220119113029_create_media_package_channels_and_origin_endpoints.rb, db/schema.rb
https://github.com/cloudnativedaysjp/dreamkast/pull/1096 でchannel_idをnull: falseにしていたが、channel_idはレコード作成時には何も値が入らないのでnullを許容する必要があった。
=> allow channel_id is null because this column value is null when record is created

app/controllers/admin/harvest_jobs_controller.rb, app/models/conference.rb, app/models/media_package_harvest_job.rb, app/models/talk.rb, app/views/admin/_navigator.html.erb, app/views/admin/harvest_jobs/_form.html.erb, app/views/admin/harvest_jobs/index.html.erb, app/views/admin/harvest_jobs/new.html.erb, app/views/admin/tracks/_tracks_nav_cndt2021.html.erb, app/views/admin/tracks/partial/_talks_table.erb, config/routes.rb, db/migrate/20220123073409_create_media_package_harvest_jobs_table.rb, db/schema.rb, lib/tasks/polling_harvest_job_and_update_video.rake
- このPRは配信・録画アーキテクチャ変更の一環で、録画アーキテクチャ部分を変更します。
- 全体の変更プランは https://github.com/cloudnativedaysjp/dreamkast/issues/989 のDescriptionを参照
- harvest_jobsテーブルを追加
- MediaLive HarvestJobを管理するためのテーブル
- admin/tracksに `録画する` ボタンを追加
- クリックするとそのHarvestJobの作成画面に遷移する
- HarvestJobの作成画面には録画開始時刻と終了時刻の入力フォームがある
- 開始時刻と終了時刻のデフォルト値はそのセッションの開始時刻と終了時刻
- 当日の進行状況によっては開始時刻・終了時刻が変わる可能性があるので変更可能になっている
- MediaPackageのタイムシフト再生と開始時刻・終了時刻を使ってプレビューできるようになっている
- HarvestJobを作成するとAWS側でアーカイブ動画の作成が行われる
- RakeタスクでHarvestJobの状態をポーリングし、アーカイブ動画の作成が完了したらHarvestJobレコードとセッションの動画URLを更新する
- RakeタスクはCronJobで定期実行することを想定
=> アーカイブ動画作成の改善

.github/workflows/cron-labeling.yml
updated_at が 3 日以上前の PR に対して `reviewapps/ignore` label を付与する GitHub Actions を作成
=> add cron-labeling Action

app/controllers/admin/harvest_jobs_controller.rb, app/jobs/delete_media_package_job.rb, app/models/media_package_channel.rb, app/models/media_package_harvest_job.rb, app/models/media_package_origin_endpoint.rb, app/views/admin/harvest_jobs/_form.html.erb, app/views/admin/harvest_jobs/index.html.erb, app/views/admin/live_stream_ivs/_ivs.html.erb, app/views/admin/live_stream_ivs/_media_live.html.erb, app/views/admin/live_stream_ivs/_media_package.html.erb, app/views/admin/live_stream_ivs/index.html.erb, lib/tasks/polling_harvest_job_and_update_video.rake
https://github.com/cloudnativedaysjp/dreamkast/issues/989
* MediaPackageのバッファ保持期間を8時間に変更
* このくらいあればまあ大丈夫じゃないかと
* HarvestJob完了時にSlack通知するように変更
* admin/live_stream_ivsのリファクタリング
* 作る順番、消す順番をadminに書いた
* ReviewAppでHarvestJob作ろうとするとエラーになるのを修正
=> アーカイブ作成周りの修正いろいろ

app/models/speaker.rb, app/models/talk.rb, spec/factories/proposal_item_configs.rb, spec/requests/speaker_dashboard/speaker_create_spec.rb
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/1125
=> プロポーザルでセッション時間の項目がない場合、タイムテーブル作成画面のセッション時間が0になる問題を修正

Gemfile, Gemfile.lock, app/middlewares/prometheus_exporter.rb, app/models/chat_message.rb, app/models/viewer_count.rb, config.ru, config/application.rb, config/initializers/prometheus.rb, spec/factories/chat_message.rb, spec/factories/talks.rb, spec/factories/videos.rb, spec/factories/viewer_counts.rb, spec/models/chat_message_spec.rb, spec/models/viewer_count_spec.rb, spec/rails_helper.rb, spec/requests/exporter_spec.rb
原案 #1127 に、以下の修正を追加
- Openedなカンファレンスのみ取得対象に
- exporterの処理部分をinitializerからmiddlewareに移行
- 情報を取得する部分はmodelに移行(役割の明確化とテスタビリティ向上のため)
- テストを追加
- config.ruに追加するのでは無くRailsの仕組みでRack middlewareを読み込むように
=> Add exporter (変更案)

app/models/speaker_announcement.rb, spec/factories/speaker_announcements.rb
モデルへのスキーマコメントで差分が発生してしまっているので修正
=> migration のモデルコメントへの適用変更漏れを修正

app/models/media_package_harvest_job.rb, app/models/media_package_origin_endpoint.rb, app/views/admin/harvest_jobs/index.html.erb, app/views/talks/partial_show/_talk_video_block_videojs.html.erb, lib/tasks/polling_harvest_job_and_update_video.rake
- 同じセッションでアーカイブ作成を複数回行った場合、後から作成されたものが使われる
- 複数回アーカイブを作っても別々のパスで保存して、talkのvideo_idを上書きすれば前のアーカイブを使えるようにする
- admin/harvest_jobsでHarvestJobで作ったアーカイブのURLを確認できるようにする
- MediaPackageでバッファする期間を24時間にする
=> improve harvest job

.github/workflows/build.yml, .github/workflows/ci.yaml, .github/workflows/gitops-prd.yml, .github/workflows/gitops-stg.yml
https://github.com/cloudnativedaysjp/dreamkast/pull/1213 が取り込まれたら入れる。
アプリケーションに関係のないMarkdownや変更対象のActionsが変更されたとき以外ビルドやテストを走らせないようにする。
CIが変わるときは加えてAction Lintも走るようになっている。
=> Ignore CI when non-code is changed

.github/workflows/ci.yml
Ref. https://github.com/ruby/setup-ruby#single-job
bundle install時のオプションは以下の箇所を見る限りは互換性の問題がなさそう。公式のものに乗っかってしまう方が良いのでお手製のActionは消してしまう。
https://github.com/ruby/setup-ruby/blob/master/bundler.js#L179
https://github.com/ruby/setup-ruby/blob/master/bundler.js#L137-L142
=> Use bundler-cache option of Setup Ruby action

app/javascript/packs/cropbox.js, app/jobs/promote_job.rb, config/initializers/shrine.rb
#1233 
Pod 内のファイルシステムにキャッシュを作成していたが, 複数インスタンスを起動して連続した処理が分散されることで 404 が発生していた
キャッシュを S3 上に `cache` プレフィックスを付けて作成するように修正した. 
cropperjs で S3 の署名付きURLを利用する場合既知の不具合が存在するらしく、`checkCrossOrigin` 属性を false に変更.
https://github.com/fengyuanchen/cropperjs#checkcrossorigin
https://github.com/fengyuanchen/cropperjs/issues/824
Promote job によって永続化に成功した場合はキャッシュは不要となるので下記どちらかの対応があると良さそう
* 定期的に時間等の条件によってキャッシュを削除するタスクを作成する
* S3 のライフサイクルを設定する
https://shrinerb.com/docs/getting-started#clearing-cache
=> 複数インスタンスあると画像のアップロードがうまくいかない

app/jobs/mail_delivery_job.rb
mail 送信時にエラーが発生していた. #1210 
主な原因は Rails 6.0 で採用されている MailDeliveryJob の仕様変更が影響していたこと.
どのタイミングで発生し始めたのかは未調査だが, Mailer に渡す第3引数が parameterize されたことによって構造が変化していた.
そのため, `args` 引数について名前付き引数に変更する必要があった.
```
args => [#Conference, #Talk, #Speaker] //期待する値 
args => { :args => [#Conference, #Talk, #Speaker] } //取得していた値 
```
https://github.com/rails/rails/pull/34367#discussion_r230235318
https://github.com/rails/rails/blob/06c116fe1a02c20ff9aa8c5f1ad96d5bcde29690/actionmailer/lib/action_mailer/mail_delivery_job.rb#L16
=> mail 送信時のエラーを修正

app/controllers/application_controller.rb, app/controllers/concerns/secured.rb, app/controllers/concerns/secured_beta.rb, app/helpers/beta_helper.rb, app/javascript/stylesheets/_beta.scss, app/javascript/stylesheets/_variables.scss, app/javascript/stylesheets/cnsec2022.scss
ベータユーザ向けにページを作成できるように concern を作成しました.
単純にページを制御するだけであれば Auth0 でロールを割り振れば行けそうです.
以下は既存の waiting ページにβ版機能を差し込む際のイメージです.
```waiting.html.erb
<%= partial_beta_view do %>
<h3>エッジの効いた機能</h3>
<span>とにかくすごい機能</span>
<% end %>
```
=> beta ユーザー専用ページを表示できる concern を追加

app/mailers/speaker_mailer.rb, app/models/speaker_announcement.rb, app/views/speaker_mailer/inform_speaker_announcement.text.erb, spec/factories/speaker_announcements.rb, spec/mailers/speaker_mailer_spec.rb, spec/models/speaker_annoucement_spec.rb
#1199 
個人宛通知を公開で作成した場合と、非公開の個人宛通知を公開にした場合に通知するようにしました。
後者については `publish_changed?` と `publish == true` で判定しているため「非公開 -> 公開 -> 非公開 -> 公開」などの場合再度通知されてしまいますが、運用上発生しえないだろうと考えたのでこの P/R ではケアしていません。
=> 登壇者お知らせの公開時に通知されなかったため、メール送信処理を追加

Gemfile, Gemfile.lock, package.json, yarn.lock
最終的にはWebpackerもおさらばしたい
> Webpacker has served the Rails community for over five years as a bridge to compiled and bundled JavaScript. This bridge is no longer needed for most people in most situations following [the release of Rails 7](https://rubyonrails.org/2021/12/15/Rails-7-fulfilling-a-vision). We now have [three great default answers to JavaScript in 2021+](https://world.hey.com/dhh/rails-7-will-have-three-great-answers-to-javascript-in-2021-8d68191b), and thus we will no longer be evolving Webpacker in an official Rails capacity.
=> upgrade webpacker

app/models/profile.rb, app/views/profiles/_form.html.erb, db/fixtures/development/privacy_policy_cnsec2022.md, db/fixtures/production/privacy_policy_cnsec2022.md, spec/models/profile_spec.rb
> ・新規登録のページで所属部署名、役職（肩書）のフリー記入欄
> ・Karteに所属部署(プルダウン)と役職区分(プルダウン)
とのことで、こちら側に所属部署名と役職を復活。
あと
- 建物名をオプションに
- プライバシーポリシーのリンクを追加
=> Fix something

app/controllers/contents_controller.rb, app/views/contents/o11y.html.erb, app/views/layouts/_event_header.html.erb
Fix #1305 
これまではO11yだけにGrafanaリンクを出していたが、これはもう常時表示にしてしまって構わない。
過去のイベントダッシュボードにも出るが、今後は過去イベントにはログイン出来なくする #1273 修正が入るし、そもそもリンクが出ても特に困らないので、この修正で常時表示にしちゃう
=> Grafanaリンクを恒常化

app/models/speaker.rb, app/models/talk.rb, spec/models/speaker_spec.rb
#1294
Track の CSV 出力にカラムを追加しました.
１点懸念点としては, プロフィール画像の URL ですが S3 のバケットが非公開のため実際には都度の署名付き URL が必要になるため CSV には有効な URL を出力できないのですがそれでも問題ないでしょうか？
後は下記確認していただきたいです.
- date の format は `2022-04-01` 
- 開催日は Talk の行われる日を出力する
- 各々のカラム名/順番について
=> add_csv_columns

db/schema.rb
https://grafana.cloudnativedays.jp/explore?orgId=1&left=%7B%22datasource%22:%22Jaeger%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22query%22:%2237f1c7007d1e9e729d61599955345d5d%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D
このクエリをかなり早くできそう（JOINさせる時にフルスキャンが走らなくなる）
```sql
SELECT 
`talks`.`id` AS t0_r0,
`talks`.`title` AS t0_r1,
`talks`.`abstract` AS t0_r2,
`talks`.`movie_url` AS t0_r3,
`talks`.`start_time` AS t0_r4,
`talks`.`end_time` AS t0_r5,
`talks`.`talk_difficulty_id` AS t0_r6,
`talks`.`talk_category_id` AS t0_r7,
`talks`.`created_at` AS t0_r8,
`talks`.`updated_at` AS t0_r9,
`talks`.`conference_id` AS t0_r10,
`talks`.`conference_day_id` AS t0_r11,
`talks`.`track_id` AS t0_r12,
`talks`.`video_published` AS t0_r13,
`talks`.`document_url` AS t0_r14, …
```
=> Add index on proposals for talks controller

app/models/talk.rb, spec/factories/talks.rb, spec/models/talk_spec.rb
#1484 
CSV の項目追加時(#1304)にCFP採択以前の状態でのダウンロードに関する実装が漏れていたことが原因のよう
=> CFP決定以前にCSVがDLできない不具合の修正

.github/workflows/gitops-prd.yml, .github/workflows/gitops-stg.yml
* `docker build` is always executed on build.yml, so I removed some lines for building image in gitopt-*.yml.
* stop to use https://github.com/cloudnativedaysjp/action-dreamkast-gitops for simplicity.
=> update actions for refactoring

docker-compose.yaml
collation is `utf8mb4_0900_ai_ci` in production, but mysql container use `utf8mb4_unicode_ci` by docker-compose.
```
mysql>  show global variables like 'collation%'
-> ;
+----------------------+--------------------+
| Variable_name        | Value              |
+----------------------+--------------------+
| collation_connection | utf8mb4_0900_ai_ci |
| collation_database   | utf8mb4_0900_ai_ci |
| collation_server     | utf8mb4_0900_ai_ci |
+----------------------+--------------------+
3 rows in set (0.01 sec)
```
=> Adjust collation to production

.github/release.yml, .github/renovate.json5, .github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/gitops-prd.yml, .github/workflows/gitops-stg.yml, .github/workflows/push-tag-by-releasebot.yml, .github/workflows/release.yml, renovate.json
* renovate
* bundle (minor, patch バージョンのみ), npm (minor, patch バージョンのみ), github-action, docker系(minor, patch バージョンのみ) でそれぞれグループ化した (グループ化した単位で PR が作成される)
* video.js は #1494 にて CI がコケているため npm のグループから除外
* renovate 産の PR には`dependencies` ラベルを付与
* .github/release.yml
* GitHub Release のテンプレートを記述
* 具体例: https://github.com/cloudnativedaysjp/seaman/releases/tag/v0.0.4
* Actions
* d141fb9
* rename: release.yml > push-tag-by-releasebot.yml
* create release.yml : タグが付与されたら GitHub Release を作成する
* update gitops-*.yml: dreamkast-infra リポジトリに出した PR を squash merge するようにした
* a127d52
* seaman によるリリース用 PR にて以下の action が走らないようにした
* build.yml
* ci.yml
* gitops-*.yml において不要行を削除
=> Update some configs for CI

schemas/swagger.yml
swagger.ymlのurl pathに誤りがあったので、修正しました。
瞬殺系なので、さっと見ていただけると助かります！
=> fix: Correct my_profile url path in swagger.yml

app/models/guest_profile.rb
GuestProfile は原則として Profile インスタンスと I/F を合わせたい。
しかし、ActiveRecord 含めスーパークラスのメソッドをすべて実装するのは難しい。
そのため迂回策として、Profile インスタンスが応答可能な method / attribute の場合は GuestProfile インスタンスでも NoMethodError を出さずに適当な値を返すようにする。
正確なクラスを返せないため、メソッドチェーンに使われているメソッドには対応できない場合もあり、その場合は GuestProfile に実装する必要がある。
=> GuestProfile インスタンスを Profile インスタンスにある程度合わせる

app/controllers/concerns/secured_public_api.rb
access_tokenからcustom claimを引いてくるところで、userからのログインであれば問題ないのですが、auth0のclient_idとclient_secretを使ったclient credential flowでのアクセス（すなわちマシンアカウントによるアクセス）の場合にuserinfoの各fieldがundefinedになってしまい、userinfoのbinding時にこける事象がでました。
userinfoについて、マシンアカウントと通常ユーザの区別をどうするよ、というところを議論すべきかと思うのですが、broadcastチームでvideo_registration endpointが叩けなくて困っているとのことなので、とりあえず入れさせてください。
（この対処が必ずしもわるいわけではなく、とりあえずuserinfoには空hashを突っ込んでおく、という整理もありかと思っています。それでよければ、追加の議論・対処不要です）
=> Not to bind userinfo for machine account access

app/controllers/api/v1/chat_messages_controller.rb, app/controllers/api/v1/debug_controller.rb, app/controllers/api/v1/profiles_controller.rb, app/controllers/api/v1/talks_controller.rb, spec/rails_helper.rb, spec/requests/api/v1/chat_message_index_spec.rb, spec/requests/api/v1/chat_message_update_spec.rb
https://github.com/cloudnativedaysjp/dreamkast-ui/pull/305 とセットで動くrails側の修正です。
dk-ui側を先にmergeしてもcookieで動きますが、こちらをmergeすることでJWTでの連携に切り替えることができます。
先にmergeしてしまうとUI側が動かなくなりますので、 https://github.com/cloudnativedaysjp/dreamkast-ui/pull/305 のmergeがblockingになります。
紛らわしいので、上記がmergeされるまではdraft PRにしておきます。
=> Use SecuredPublicApi for ChatMessages and Profiles

config/default.conf
local devしているときに、 `(.*)/ui/...` とネストされたリソースにアクセスしたときに一律 `/ui` にroutingされてしまっていて、画像が表示されなくなっていたので、location directiveを追加しました。
まとめることもできそうな気がしたのですが、 trailing slashがないケースがうまく動かず、諦めてこの構成にしています。。。
良い案があれば教えてほしいです。
また、現在は `ui/...` にはimage assetsしか配置してないのでproxy_passだけで良いかなと思ったのですが、将来的に他のページをnextで追加する可能性もあるかなと思い、 `/ui` と同じ定義に揃えています。
=> Nginx config to route sub-pages including image assets

config/default.conf
nextのhot reloadのws通信が通ってなかった問題を直しました。
reloadすればよいだけではあるのですが、css周りをいじるときは重宝するのと、ひたすらwebsocketの再試行が走っていて煩わしくもあるので...
wsを通すdirectiveを追加しています。
=> chore: Fix nginx config to pass next webpack-hmr

Dockerfile, docker-compose.yaml
docker-compose上でfifo-workerを動かした時、RAILS_ENVがproductionになる。railsをlocalで動かした時はRAILS_ENVはdevelopmentになる。これにより使われるActionCableの設定が変わり、broadcastがうまく動かなくなっていた。
開発ではproductionではなくdevelopmentを使う方がよいだろうから、developmentを使うように修正。
=> fifo-workerをdocker-compose上、railsをlocalで動かした時にActionCableのbroadcastが動かない問題を修正

app/views/api/v1/profiles/my_profile.json.jbuilder, schemas/swagger.yml
https://github.com/cloudnativedaysjp/dreamkast-ui/pull/332 でUIに登録済みセッションを表示するページを追加するのだが、そのページに必要な登録済みセッションに関する情報をmy profile apiで返すようにします。
=> add registered talks to display registered talks in dreamkast-ui

config/default.conf
local devでSAMを叩くためのnginxのproxy routing追加です。
とりあえず動作確認したければ、cdkとsamをインストールして、dreamkast-functionにてこれを実行してもらえると動きます。
```
EVENTABBR=cndt2022 cdk synth -c config=dev --no-staging && sam local start-api -t cdk.out/stateless-dev.template.json -p 3002 --profile <your_profile> --debug
```
SAMをcontainerで動くようにしてdocker-composeでさっと立ち上げられるようにしたいですが、そこまではまだできていません。
SAMはlocalのport: 3002にで動かして、そこにnginxでつなぎにくるだけの構成です。
=> Additional location directive of nginx to address local SAM

schemas/swagger.yml
https://github.com/cloudnativedaysjp/dreamkast-functions/pull/52
上記のapigatewayの変更分を、swagger.ymlに反映しました。
加えて、dk-functionのapiにすべて `dreamkast-function` が入っていましたが、tagが入っているとRTK Queryのmutation後にreloadする対象と判定されてしまうため、関連があって必要なところのみtagをつけるようにしました
=> chore: Port swagger.yml from the apigateway exported one

app/models/talk.rb
キーノートの残席がTrackAのみになっていて売り切れているが、実際には他の部屋でパブリックビューイング出来るので、キーノートだけ残席を会場全体の数にするワークアラウンド。
本当はキーノートかどうかをフラグで判断したかったが、キーノートなのにキーノートカテゴリにしていないセッションも多いため苦肉の策でID直指定している。今回のみのワークアラウンドとしたい
=> Workaround to fix number of seet for keynotes

app/models/talk.rb
現在/api/v1/talksをcallすると11/1のプレイベントの夜イベの値が帰ってくるが、SLOT_MAPの値を超過していてfor loopでヒットせず、結果SLOT_MAP自体が返されてしまいjbuilder側の `to_i` でエラーを引き起こしていたので、値を追加しました。
本番は発生しない気がしつつ、夜イベで影響がでないとも限らないので、予防です
=> fix: Extend SLOT_MAP to avoid out of range

app/views/talks/partial_show/_col_main_pane.html.erb
=> CNDT2022のアーカイブ表示を一時的に止める

app/controllers/talks_controller.rb
これは暫定的な対処で、カンファレンスのStatusを改善した後適切な条件分岐で直します
=> registeredの場合はshow_on_timetable=trueなTalkを全て表示する

app/models/conference.rb, db/migrate/20221219102416_add_conference_status_to_conferences.rb, db/schema.rb, spec/factories/conferences.rb, spec/models/conference_spec.rb
statusは数値で扱っているが、新しい状態を追加するときに数値の順序を考慮すると面倒なので、文字列で扱えるようにする。
まずは新しいカラムを追加して、既存のConferenceについてstatusと値を揃える。
このPRの変更では動作の変更はない。
この後、別PRで新しいカラムを使うように変更する予定。
https://github.com/cloudnativedaysjp/dreamkast/discussions/1368
=> カンファレンスの状態改善その1

app/forms/conference_form.rb, app/models/conference.rb, app/views/api/v1/conferences/index.json.jbuilder, app/views/api/v1/conferences/show.json.jbuilder, spec/factories/conferences.rb, spec/requests/timetable_spec.rb
https://github.com/cloudnativedaysjp/dreamkast/pull/1719 の後にマージ＆リリースする。
https://github.com/cloudnativedaysjp/dreamkast/pull/1719 で追加した `conference_status` カラムを使うように全体を変更する。
このPRの後、statusカラムを削除する。
https://github.com/cloudnativedaysjp/dreamkast/discussions/1368
=> カンファレンスの状態改善その2

.gitignore, Dockerfile.dev, README.md, compose-dev.yaml
必要ファイル (.env)を用意した後に
```
docker compose -f compose-dev.yaml up -d
```
だけで開発環境が上がるようにした。
DockerのDev Environmentとの互換性を考慮して `compose-dev.yaml` を使うようにしている。
=> Improve experience for local development

app/controllers/api/v1/talks_controller.rb, spec/factories/talks.rb, spec/requests/api/v1/talk_index_spec.rb
conferenceDayIdsを指定しない場合、rejectedなtalkも返そうとするが、それらにはstart_timeが設定されていないのでjsonのビルドでエラーになる。
`v1/talks` APIの返値にrejectedなtalkを含む必要はないと思われるため、AcceptedなセッションもしくはIntermissionのみ返すようにします。もしrejectedなtalkもAPIで取得する必要がある場合は `v1/proposals` のようなAPIを別途追加します。
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/1616
=> fix: return error if omitting conferenceDayIds param

app/controllers/concerns/secured.rb, app/controllers/event_controller.rb, app/views/event/preparation.html.erb, config/routes.rb
#1771 
以下の対応を追加
- ログイン状態で一般参加申し込み不可の状態でアクセスすると準備中ページに遷移するように変更
- 一般参加期間前なのと、参加者情報の編集もできなくなるので一旦参加者登録自体をブロック
特に後者の変更については機会損失の可能性もあると思うので、ちょっとご相談させてください。
編集には今のところチケット情報が必要になるので編集だけ可というのはすぐには難しいです。
下記スクショでは「SessionListを利用する場合」になっていますが、実際は「本サイトを利用する場合」になっています。
=> 一般参加申し込み前の操作ができなくなる現象の対応

app/controllers/admin/conferences_controller.rb, app/forms/conference_form.rb, app/javascript/stylesheets/_admin.scss, app/views/admin/conferences/_form.html.erb, app/views/admin/conferences/edit.html.erb, db/fixtures/development/00_seeds.rb, db/fixtures/production/00_seeds.rb
事務局からの要望で、プライバシーポリシーを管理画面で変更できるようにした。
これはスポンサーが随時追加されるについれ、プライバシーポリシーの情報提供先企業のリストを更新する必要があるため、事務局作業のセルフサービス化の一環で追加。
=> Privacy policyをAdminページから登録するように

config/initializers/sentry.rb
トランザクションのサンプルレートが大きいため、キャパシティを越えてしまっている。今あまりみられていないし、1％に下げても問題ないと思う。普段だと1%は数が少なそうだが、イベント中であれば1%でもある程度パフォーマンスの測定には使えるだろう。
https://docs.sentry.io/platforms/ruby/configuration/sampling/
=> chore: decrease rate for transaction

app/helpers/media_live_helper.rb, app/helpers/media_package_helper.rb, app/helpers/ssm_helper.rb, app/models/live_stream_ivs.rb, app/models/live_stream_media_live.rb, app/models/media_package_harvest_job.rb, config/initializers/aws.rb, lib/tasks/aws.rake
AWS 上のリソースが以前のものが残っていたのもあり、基本は #1345 の revert のままにしました。
今後 region 変更の可能性などを踏まえてグローバル定数に region を定義するようにしています。
admin 画面からリソースを作成し、OBS で配信できることと rtmp で視聴できることを確認しました。
Infra への対応は不要かと思いますが、その点ご確認いただければと思います。
=> LiveStream の region を US に変更する

app/controllers/api/v1/speakers_controller.rb, app/views/api/v1/speakers/index.json.jbuilder, config/routes.rb, schemas/swagger.yml, spec/requests/api/v1/speaker_index_spec.rb
website用にスピーカー情報を取得するためのAPIを追加する。APIで取得できるのはdk本体でパブリックな情報として見えるもののみとするので認証など不要にしているが、もし認証書けておいた方がよいのではなどコメントあればください。
=> feat: add speakers api

schemas/swagger.yml
CNDT2022の最後の追い込みで、apigatewayから出力したswagger.ymlをdkを通している時間が惜しかったのでdreamkast-uiに直接渡していました。結果dkとdk-uiのswagger.ymlが不一致な状態なので、それを解消するPRです。
もう少しあるかと思っていましたが、差分は2行だけでした。
これをmergeしてgithub actionが走っても、dk-ui側のRTK query clientの更新PRは作成されないはずです（変更点がないので）
=> fix: Update swagger to the one used at dreamkast-ui

compose-dev.yaml, docker-compose.yaml
docker-composeで起動するdk-uiが古く、かつ環境変数がアタッチされておらず動かない状態だったので、動くように修正しました。
dk-uiは、main mergeされるとそのrevisionで生成されたdocker imageにlatestタグが付くように修正しています。
https://github.com/cloudnativedaysjp/dreamkast-ui/pull/368
=> fix: make dk-ui work when started by docker-compose

lib/tasks/post_number_of_registrants_to_slack.rake
conversations_listがページネーションされておらず、チャンネル一覧にcicd2023が含まれていなかった。そのため通知されていなかった。
=> need pagination

config/environments/development.rb
Action cable側の設定変更が漏れていて、local dev時のcorsアクセスができない状態だったので、修正しました。
=> fix: update action-cable allowed-request-origins to enable websocket cors access

app/models/talk.rb
2000以降のSLOTがないので、夜間のセッションがある際にtalks apiが500エラーになる。
=> fix: SLOT_MAPに2000以降の項目を追加

app/views/api/v1/sponsors/index.json.jbuilder
CICD2023でadminからスポンサー情報を登録できるようにしたのだが、その際ロゴの情報を持たせるフィールドが `url` から `file_data` に変えていた（S3にアップロードするので変更が必要だった）。そのため、sponsor apiがCICD2023のスポンサー一覧を返そうとした際にurlがnilのためエラーになっていた。
```
irb(main):020:0> Conference.find_by(abbr: 'cndt2022').sponsors.map{|sponsor| [sponsor.name, sponsor.sponsor_attachment_logo_image.url]}
=>
[["CircleCI合同会社", "sponsors/cndt2022/circleci.png"],
["LINE株式会社", "sponsors/cndt2022/line.png"],
["Snyk株式会社", "sponsors/cndt2022/snyk.png"],
["テクマトリックス株式会社", "sponsors/cndt2022/techmatrix.png"],
["GMOインターネットグループ株式会社", "sponsors/cndt2022/gmo.png"],
["PingCAP株式会社", "sponsors/cndt2022/pingcap.png"],
["PagerDuty株式会社", "sponsors/cndt2022/pagerduty.png"],
["Aiven Japan合同会社", "sponsors/cndt2022/aiven.png"],
["グーグル・クラウド・ジャパン合同会社", "sponsors/cndt2022/google.png"],
["クリエーションライン株式会社", …
```
=> CICD2023以降ではsponsor logoの持ち方が変わっていたのでAPIをそれに対応させる

db/fixtures/development/00_seeds.rb, db/fixtures/production/00_seeds.rb, lib/tasks/add_talks_for_cicd2023_rehearsal_dummy_sessions.rake, lib/tasks/add_talks_for_cicd2023_rehearsal_intermission.rake
**staging環境**に対して、以下の順でRakeタスクを実行する。リハーサル用のConferenceDayはデプロイ時に自動的に作られる。
1. add_talks_for_cicd2023_rehearsal_dummy_sessions
2. add_talks_for_cicd2023_rehearsal_intermission
=> Add rake task to add session for staging

app/controllers/admin/talks_controller.rb, spec/factories/talks.rb, spec/requests/admin/talks_spec.rb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/1852
- 別日にオンエア状態のTalkがある時のバリデーションが一部動いていなかった問題を修正
- Start/Stop後にメッセージ表示されなくなっていた問題を修正
- パフォーマンス修正
=> fix: validation when start_on_air

.github/renovate.json5
renovateが作るPRについてのルールをヘッダとして追加します。PRのテンプレートは設定で変えられる模様。
https://docs.renovatebot.com/configuration-options/#prheader
close https://github.com/cloudnativedaysjp/dreamkast/issues/1878
=> add rule for PR by renovate

app/controllers/admin_controller.rb, app/views/admin/statistics.erb
現地参加・オンライン参加の人数表示はどうやるか検討中なので、一旦セッション毎の登録者数のみadminで見えるようにする
close https://github.com/cloudnativedaysjp/dreamkast/issues/1857
=> セッション毎の登録者数をadmin/statisticsに表示する

docker-compose.yaml, localstack/docker-entrypoint-initaws.d/README.md, localstack/init/ready.d/create_queue.sh
- localstack:latestをimage pullしてdocker-composeで起動すると、sqs queueが作られずhealthcheckが通りませんでした。
- 新しいlocalstackは起動時のinterceptの仕方が変わったようなので、新しいimageにも対応できるようにmount pointを追加しました。
- ref: https://docs.localstack.cloud/references/init-hooks/
- mount先を増やすだけでも良かったのですが、新しい方式の方がhookできるポイントが増えていて柔軟性が高そう & ディレクトリ構成がわかりやすいので、そちらに揃えました。
- 後方互換のため、古い方も残しています
=> chore: Move localstack init script to catch up to the latest init process

app/controllers/concerns/secured.rb, app/controllers/concerns/secured_admin.rb, app/models/conference.rb, spec/factories/conferences.rb, spec/requests/admin/speaker_announcements_spec.rb, spec/requests/admin/speakers_spec.rb, spec/requests/admin/talks_spec.rb, spec/requests/admin_spec.rb, spec/requests/event_spec.rb, spec/requests/talks_spec.rb
- Conferenceのstatusをmigratedに変更するとリダイレクトする
- セッションのパーマネントリンクはwebsiteの対応するパーマネントリンクにリダイレクトする
- それ以外のURLはwebsiteの各イベントトップページにリダイレクトする
- adminにアクセスした際にログインしていないとトップページにリダイレクトしていたが、ログインページにリダイレクトするように変更
https://github.com/cloudnativedaysjp/dreamkast/issues/1895
=> Support redirect to website

app/helpers/application_helper.rb, app/javascript/packs/vote_cfp.js, app/views/talks/partial_show/_col_main_pane.html.erb, compose-dev.yaml
fix: #1896 
CFP の投票先を dk-weaver に切り替えました。
GraphQL のクエリは #1896 に準拠しつつ、コミットが進んだ分を追従しています。
環境変数から URL を取得していましたが、キー名を `DREAMKAST_API_ADDR` から `DREAMKAST_WEAVER_ADDR` に変更していますので、そちらにも対応が必要になりますが、こちらはまだ確定していないとのことなので現段階では未対応です。
WEAVER へのリクエストが失敗した場合にはアラートで対応するように仕様を変更していますが、こちらサーバーレスポンスが失敗した場合（500エラーなど）にはアクションが何も起こらない状態です。
この変更については検討の余地ありだと思いますので、（エラーハンドリングの場合分けを追加する/エラーは無視して投票済みへの切り替えを行う等）、ご意見をお伺いしたいところです。
=> cfp投票先をdk-weaverに切り替え

app/controllers/talks_controller.rb
fix: 1903
/talks で proposal が見えない問題を修正しました。
一応自分のローカルでは修正を確認していますが、seed データの問題などの可能性もあるので、ローカルもしくは ReviewApp での確認をお願いしたいです。
=> fix talks page is blank

app/controllers/api/v1/conferences_controller.rb
`/api/v1/events` 呼び出し時にconference_daysの取得クエリがイベントの数だけ呼ばれていて非効率なのを修正
=> Fetch conference days in single query to improve performance

app/views/talks/partial_show/_col_main_pane.html.erb, spec/factories/conferences.rb, spec/requests/talks_spec.rb
close https://github.com/cloudnativedaysjp/dreamkast/issues/1911
=> タイムテーブルを非表示にしていてもセッション個別ページに表示されてしまっている

Gemfile, Gemfile.lock
Capybara を始め E2E 関連の Gem がいくつか renovate されていたが、現状 E2E テスト（実際に UI を描画して動かすテスト）は実施しておらず、また直近導入予定もないので削除しておきたい。
また、bundle install 時に rubyzip がバージョン警告を出しているがこれは Capybara の依存関係としてしか取り込まれていない。
=> remove e2e gems

app/helpers/env_helper.rb
環境変数でprod/stagingなど識別できるようにした方がいいが、それは別途やります
=> env_nameの条件にS3バケット名を使っていて、バケットを変えたので正しくenv_nameが出なくなった問題を修正

app/models/profile.rb
industryの構造が変わったためfindで取得できなくなっていた
https://github.com/cloudnativedaysjp/dreamkast/issues/1976
=> 参加者エクスポートがエラーになるのを修正

app/views/admin/speakers/_form.html.erb, app/views/attendees/index.html.erb, app/views/speakers/index.html.erb, app/views/speakers/show.html.erb
数か所でサイズ指定のないサムネイル表示があり、元画像を表示していたためサイズ指定に修正
=> サムネイルサイズの指定の誤りを修正

app/views/attendees/index.html.erb
crop できていない画像の場合 `avatar_url(:medium)` の部分で失敗してエラーになっているので追加修正
=> crop に失敗した画像の場合元画像を出すようにする

app/models/talk.rb, spec/models/talk_spec.rb
Fix #2001
2001の修正方法として
- 既に別日でOnAirのTalkがある場合は受け付けない
- 別日でOnAirがあった場合は、そちらをオフにしてリクエスト側をオンにする
の2つのアプローチがあるが、UIは前者のアプローチでバリデーションしている。これはUIの構成上誤操作のリスクがあるので好ましい動作。
しかしAPIの利用シーン的には後者のほうが便利だし、誤操作のリスクはそれほど高くない(talk_idを明示するので曜日を誤指定することは考えづらい)
そのため、フィルタリング条件を変更して別日であっても自動的にオフになるようにした
=> Offair talks having same track id and different conference_day_id

app/views/speaker_dashboard/speakers/_presentation_method.html.erb, app/views/speaker_dashboard/speakers/_session_times.html.erb, app/views/speaker_dashboard/speakers/_talk_fields.html.erb
CFP のフォームでチェックボックスとラジオボタンが input のみに入力判定があり、ラベルの文字列をクリックしても反応しない状態だったのでラベルでも入力できるようにしました。
=> checkbox と radio_button をラベルリンクする

.github/workflows/build.yml
Graviton対応に向けて、ARM対応イメージをビルドするBuildjetを追加する。
懸念事項
1. 実行する時間帯によってbuildjetによるビルドがいつまでも終わらないケースがある。
- 通常約8分で終わるところ、17分以上かかっても終わらない
- 正常終了したworkflow
- https://github.com/cloudnativedaysjp/dreamkast/actions/runs/5914172251
- 終了しないworkflow
- https://github.com/cloudnativedaysjp/dreamkast/actions/runs/5912169199
- 22時以降に実施すると終わらない場合が多い。
- 朝、日中に実施した場合は問題なし。
- buildjet側のstatusにパフォーマンス低下の通知が来ているがリアルタイムには分からない
- https://status.buildjet.com/
=> workflowにBuildjetを追加

.github/workflows/build.yml
https://github.com/cloudnativedaysjp/dreamkast/actions/runs/6098184501
buildjet によるbuildに2時間かかっているケース↑があるため以下の対策を実施。
- githubactionのworkflowにtimeout(10分)を設定
- timeoutした場合、手動で再実行、もしくは実行時間を変えて再実行していただく。
- 2vcpu→4vcpuに変更
- timeoutと合わせて設定することで過剰な課金は防止できる。
- buildに10分かかった時点でtimeoutで停止すること
- https://github.com/cloudnativedaysjp/dreamkast/actions/runs/6111269796
- 10分以内の場合は正常終了すること
- https://github.com/cloudnativedaysjp/dreamkast/actions/runs/6111477998
=> GithubActionにtimeoutを設定

app/controllers/admin/streamings_controller.rb, app/controllers/api/v1/streamings_controller.rb, app/jobs/create_streaming_aws_resources_job.rb, app/jobs/delete_streaming_aws_resources_job.rb, app/models/conference.rb, app/models/streaming.rb, app/models/track.rb, app/views/admin/_navigator.html.erb, app/views/admin/streamings/index.html.erb, app/views/api/v1/streamings/index.json.jbuilder, config/routes.rb, db/migrate/20230627103419_create_streamings_table.rb, db/schema.rb, spec/factories/streamings.rb, spec/requests/admin/streamss_spec.rb
MediaLiveやMediaPackage, MediaPackageV2などのリソースをまとめて管理するためのテーブルとモデルを作成します。
Streamingオブジェクトを作成し、`create_aws_resources` や `delete_aws_resources` メソッドを呼ぶことで非同期で必要なリソースを作成する予定です。
管理画面に `/admin/streamings` を追加しており、今後はこの画面からAWSリソースを作成します。このPRの時点では以下の操作のみ可能です。
- Streamingレコードを作成
- 作成したStreamingレコード経由でAWSリソース作成メソッドを呼び出す（現時点では何もしない）
- 作成したStreamingレコード経由でAWSリソース削除メソッドを呼び出す（現時点では何もしない）
Streamingレコード自体は削除する必要はないので削除用処理は未実装です。
=> AWS上の配信用リソースを管理するためのstreamingsテーブルとStreamingモデルを追加する

Gemfile, Gemfile.lock, app/helpers/media_package_v2_helper.rb, app/jobs/create_streaming_aws_resources_job.rb, app/jobs/delete_streaming_aws_resources_job.rb, app/models/media_package_v2_channel.rb, app/models/media_package_v2_channel_group.rb, app/models/media_package_v2_origin_endpoint.rb, app/views/admin/streamings/index.html.erb, db/migrate/20230906132249_create_media_package_v2.rb, db/schema.rb, spec/factories/media_package_v2_channel.rb, spec/factories/media_package_v2_channel_group.rb, spec/factories/media_package_v2_origin_endpoint.rb, spec/requests/admin/streamss_spec.rb
https://github.com/cloudnativedaysjp/dreamkast/pull/2019 の後続PR。
このPRではMediaPackageV2リソースを扱えるようにする。 `/admin/streamings` でStreamingレコードを作ると非同期にMediaPackageV2のChannelGroup, Channel, OriginEndpointが作られる。これらのリソースはTrack毎にそれぞれ作成される。
なお、このPRでは細かいパラメータのチューニングは行わない。
=> (1) MediaPackageV2リソースを扱えるようにする

app/helpers/media_package_helper.rb, app/jobs/create_media_package_job.rb, app/jobs/create_streaming_aws_resources_job.rb, app/jobs/delete_media_package_job.rb, app/jobs/delete_streaming_aws_resources_job.rb, app/models/media_package_channel.rb, app/models/media_package_origin_endpoint.rb, app/models/media_package_parameter.rb, app/models/streaming.rb, app/models/track.rb, app/views/admin/streamings/index.html.erb, db/migrate/20230909035236_add_streaming_id_columns_to_media_package_tables.rb, db/schema.rb
https://github.com/cloudnativedaysjp/dreamkast/pull/2020 の後続PR。
このPRでは既存のMediaPackage系リソースをStreamingリソースの管理下に移行します。また、MediaLiveからMediaPackageに送るために必要なパラメータを扱うためのテーブルも追加しています。
=> (2) MediaPackageリソースをStreamingの管理下に移行する

app/javascript/stylesheets/cndt2023/_cndt2023.scss, app/views/event/preparation.html.erb, app/views/talks/show.html.erb
- ログアウトしないとCFP一覧が見れないので、その旨が分かりやすいように文言を修正
- ロゴが被って個別セッションのタイトルが隠れていたのを修正
- スマホだとロゴがデカすぎるので調整
=> Change preparation message

app/views/event/partial/_information.html.erb, app/views/event/partial/_speaker_entry_button.html.erb, app/views/event/preparation.html.erb, app/views/layouts/_event_header.html.erb, app/views/speaker_dashboard/speakers/_form.html.erb, app/views/speaker_dashboard/speakers/_speaker_info.html.erb, app/views/speaker_dashboard/speakers/edit.html.erb
- SessionListだと視認性が悪かったので、CFP期間は「プロポーザル一覧」 それ以外は「セッション一覧」「タイムテーブル」と切り替わるようにした
- SessionListの中にさらにプルダウンだったのを、平置きのリンクに変えた
- 登壇者登録の下にプロポーザル一覧ボタンを設置
- TwitterをX(Twitter)表記に
- ボタンのスタイルをあてた
- 開催概要のキーワードがo11yのままだった
=> ナビゲーション改善 & レビュー反映

.github/workflows/build.yml
`Docker meta`がpush tagでも起動するようにトリガーを追加
=> Docker metaにトリガーを追加

app/views/event/cndt2023_show.html.erb
Speakers のスタイルが名前の長さで伸び縮みしていたので `width: min-content` で文字溢れを修正しました.
その分縦幅が不ぞろいになりますが, 登壇者の名前を (...) で省略するのも良くないかなと思い, 横幅のずれよりは気になりにくいだろうということで縦に伸ばしています. 
下記はとりあえず本番で CSS を書き換えてみた例です.
=> Speakers のスタイルを修正

app/controllers/profiles_controller.rb
チェックイン機能を修正
あと2022スタンプラリー向けの機能は不要になったので削除。
既存レコードのチェックをしていないので、何回でもチェックインが出来てしまいそのたびにレコードが作られるが、これはこれで1日目と2日目それぞれチェックインさせるみたいな利用も可能になるので、このままで良いかなと
=> Fix check-in

app/controllers/attendee_dashboards_controller.rb, app/controllers/event_controller.rb, app/views/attendee_dashboards/show.html.erb, spec/requests/tracks_spec.rb
- conferenceがopenedの時でも `/dashboard` を見えるようにする
- conferenceがopenedの時、 `/dashboard` からUIへの導線を追加
- `/cndt2023` アクセス時、conferenceがopenedの時はUIにリダイレクトする。
UIからダッシュボードへの導線は https://github.com/cloudnativedaysjp/dreamkast-ui/pull/477 で追加します。
=> イベント開催中にダッシュボードを閲覧できない問題を解消する

app/middlewares/dreamkast_exporter.rb, app/models/proposal_item.rb
#2059　の修正版。
メトリクス`dreamkast_select_proposal_items`のlabelsにtalk_idを追加することで正しく件数を取得する。
=> Proposalに関する情報をExporterで出力できるようにする

lib/tasks/cleanup_profiles.rake, spec/rake/cleanup_profiles_spec.rb
conferenceに `migrated` ステータスを追加していたのでcleanupスクリプトでも対応する
=> fix: cleanup script

app/controllers/api/v1/proposals_controller.rb, app/views/admin/proposals/index.html.erb, spec/factories/talks.rb, spec/requests/api/v1/proposal_index_spec.rb
#2076 
Session type の Talk だけを表示するように修正しました。
また、Session type カラムが追加された変更に合わせて管理画面のプロポーザルリストのカラムを SponserSession? から Type に変更しました（Keynote？を追加するよりは Type で一覧表示した方がよいかなという判断でした）。
=> Proposal APIにKeynoteやスポンサーセッションが含まれてしまっている問題の修正

.github/workflows/ci.yml
- フォークされたリポジトリからのPRについて、CI内のSimplecov Reportがコケる
- secrets.GITHUB_TOKENに権限がないため https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
- そのため、permissionsでpull-requests: write権限を追加する
-  フォークされたリポジトリからのPR のようなoutside collaboratorからのPRについて、CIはcontributorのapprovalがないと動かないのでセキュリティ的にも問題はなさそう
=> add permission to comment PR

spec/requests/api/v1/chat_message_index_spec.rb, spec/requests/api/v1/chat_message_update_spec.rb, spec/requests/api/v1/conference_index_spec.rb, spec/requests/api/v1/conference_show_spec.rb, spec/requests/api/v1/event_show_spec.rb, spec/requests/api/v1/proposal_index_spec.rb, spec/requests/api/v1/speaker_index_spec.rb, spec/requests/api/v1/sponsor_index_spec.rb, spec/requests/api/v1/talk_index_spec.rb, spec/requests/api/v1/talk_show_spec.rb, spec/requests/api/v1/track_index_spec.rb, spec/requests/api/v1/track_show_spec.rb, spec/requests/api/v1/video_registration_spec.rb
Since committee gem v4.4.0, `assert_response_schema_confirm` requires HTTP status code explictly.
Been seeing this message a lot in the logs, so fix that up.
> Pass expected response status code to check it against the corresponding schema explicitly.
Also, since we're now testing response status code with `assert_response_schema_confirm(200)`,
so we no longer need our own test `expect(response).to(have_http_status(:ok))`.
=> Suppress committee warning

config/environments/test.rb, lib/tasks/cleanup_profiles.rake, spec/rails_helper.rb
Changing log level during testing generates a large amount of unnecessary log messages.
This change ensures the use of the default logging configuration in tests, thereby simplifying the focus on test results.
=> Disable SQL log in test

Gemfile, Gemfile.lock
In PR #1103, awesome_nested_set gem is specified directly from GitHub to support Rails 7.
(At that time v3.5.0 had not been released yet.)
Revert to using gem from the RubyGems repository.
NOTE: awesome_nested_set v3.6.0 has been released.
https://github.com/collectiveidea/awesome_nested_set/compare/3913eca598...v3.6.0
=> Use released awesome_nested_set gem

compose.yaml, localstack/docker-entrypoint-initaws.d/README.md, localstack/docker-entrypoint-initaws.d/create_queue.sh
The new method for initializing localstack using `/etc/localhost/init/<stage>.d` was introduced in [v1.1.0](https://github.com/localstack/localstack/releases/tag/v1.1.0) (2022-09-03). It's been more than a year since this update was released. Time to clean up deprecated code.
See: PR #1886
=> Remove DEPRECATED /docker-entrypoint-initaws.d

spec/models/profile_spec.rb
Accidentally, we were testing the `email` field instead of `company_email` (Testing `email` field validation twice).
=> Fix validation test for `company_email` to target the correct field

app/controllers/application_controller.rb
pundit gem v2.2.0 outputs the following deprecation warning:
> 'include Pundit' is deprecated. Please use 'include Pundit::Authorization' instead.
>  (called from Module#include at /Users/onaka/src/github.com/cloudnativedaysjp/dreamkast/app/controllers/application_controller.rb:7)
https://github.com/varvet/pundit/blob/v2.2.0/CHANGELOG.md
When a top-level module is included, many side effects occur, such as the creation of the `VERSION` constant.
As a result, `Pundit::Authorization` module has been separated.
=> Fix pundit deprecation warning

Gemfile.lock
Fix following warning:
> /Users/onaka/src/github.com/cloudnativedaysjp/dreamkast/app/helpers/application_helper.rb:94: \
> warning: undefining the allocator of T_DATA class Redcarpet::Markdown
From Ruby 3.2, warnings are displayed when C extensions undefine or redefine the alloc functions for `T_DATA` objects. https://bugs.ruby-lang.org/issues/18007
* https://github.com/vmg/redcarpet/blob/v3.6.0/CHANGELOG.md
* https://github.com/vmg/redcarpet/compare/v3.5.1...v3.6.0
=> Update redcarpet gem

app/views/admin/tracks/index.js.erb, app/views/admin/tracks/partial/_debug_media_live_information.html.erb
To render this partial template, we get `#debug_media_live_information` node from JavaScript and fill it with its `innerHTML`. But, this HTML node was removed in PR #2060. Now, there's no place for it.
=> Remove unused debug_media_live_information

config/routes.rb
before:
```
GET    /:event/profiles/new(.:format) profiles#new
GET    /:event/profiles/new(.:format) profiles#new
POST   /:event/profiles(.:format)     profiles#create
POST   /:event/profiles(.:format)     profiles#create
DELETE /:event/profiles/:id(.:format) profiles#destroy
DELETE /:event/profiles(.:format)     profiles#destroy
DELETE /:event/profiles/:id(.:format) profiles#destroy_id
```
after:
```
GET    /:event/profiles/new(.:format) profiles#new
POST   /:event/profiles(.:format)     profiles#create
DELETE /:event/profiles(.:format)     profiles#destroy
DELETE /:event/profiles/:id(.:format) profiles#destroy_id
```
memo:
`profiles#destroy` searches for the target Profile from session, and `profiles#destroy_id` searches for the target Profile in `params[:id]`.
Normally, if …
=> Fix duplicate routes

app/controllers/admin/proposals_controller.rb, app/controllers/admin/talks_controller.rb, app/controllers/admin/tracks_controller.rb, app/models/talk.rb, spec/models/talk_spec.rb
Change `Talk.export_csv` to use `./tmp/`, align with other CSV export paths used in `admin/speakers#export_speakers` and `admin/profiles#export_profiles`.
Also did a bit of refactoring; see each commit for details.
=> Align CSV export path to ./tmp/ directory

spec/requests/admin/speakers_spec.rb, spec/requests/admin/talks_spec.rb, spec/requests/admin_spec.rb
This change is split into two parts:
* Resolved the cause of the skipped test:
- The test was not correctly receiving `params[:event]`, leading to an incorrect redirection to `//registration` instead of `/:event/registration`
- Modified the test to correctly redirect to `/:event/registration`, aligning with the intent at the time the test was written
* Updated the test to reflect the current implementation:
- Following PR #854, the behavior has changed from a redirect to returning a 403 status
- Adjusted the test to now expect a 403 Forbidden status
=> Implement skipped request spec

app/models/room.rb, db/migrate/20240416161214_remove_track_id_from_rooms.rb, db/schema.rb, spec/factories/rooms.rb
Given the relationship where Room `has_one` Track and Track `belongs_to` Room, the `track_id` column in the `rooms` table is not used.
See: PR #1559
=> Remove unused track_id column from rooms table

app/controllers/speaker_dashboards_controller.rb, app/controllers/sponsor_dashboards/sponsor_dashboards_controller.rb
`logged_in_using_omniauth?` before_action is enabled in all `SecuredSponsor` or `SecuredSpeaker` modules.
=> Remove duplicate call of logged_in_using_omniauth?

app/controllers/concerns/secured_public_api.rb
Currently, the `current_user` method is used as a setter, which can be misleading due to its name. To improve clarity and reduce confusion, rename this method to `set_current_user_from_claim`.
This change is to prepare for adding new `current_user` method in the following Pull Request.
=> Rename `current_user` to avoid confusion

app/controllers/admin/talks_controller.rb, app/controllers/admin/tracks_controller.rb, app/helpers/admin/talk_table_helper.rb, spec/factories/talks_speakers.rb, spec/helpers/admin/talk_table_helper_spec.rb
`TalkTable` module contains only helper methods and has no methods intended for use in controllers. According to Rails best practices, methods only used in views should be in the helpers directory.
=> Move TalkTable from controller concerns to helpers

app/javascript/packs/speaker_form.js
If using `window.onload`, addEventListener runs before complete render dom. In that case, `add session` button have no event listener.
reproduction steps:
1. Go to `/cnds2024/admin/sponsors` and add sponsor. Add your email into speaker list.
2. Go to `/cnds2024/sponsor_dashboards/login` . Input your name and proceed form, you can open `/cnds2024/sponsor_dashboards/${sponsor_id}/speakers/new` that is form for inputting sponsor speaker and sponsor session.
3. Click `セッションを追加する` . Expected behavior is adding form for session, but nothing happens.
=> fix: An issue where the form adding a session would not be displayed and would be reloaded when the `add session` button was pressed

app/controllers/concerns/secured.rb, app/controllers/logout_controller.rb
Rails 7.0 introduced open redirect protection as a new security feature.
Dreamkast is currently running on Rails 7.0 but has not fully transitioned to the defaults (with `new_framework_defaults_7_0.rb` still pending updates).
This commit prepares for Rails 7.0 default settings, including open redirect protection.
=> Prepare for enabling open redirect protection in Rails 7.0

app/views/speaker_dashboard/speakers/_form.html.erb
speaker_form.js is imported in form.html, but it's already imported in cnds2024.js.
=> fix: an issue where two forms were added when clicking `add new session` in sponsor session form

app/controllers/application_controller.rb, app/controllers/attendees_controller.rb, app/controllers/concerns/secured.rb, app/controllers/concerns/secured_admin.rb, app/controllers/concerns/secured_api.rb, app/controllers/concerns/secured_beta.rb, app/controllers/concerns/secured_speaker.rb, app/controllers/concerns/secured_sponsor.rb, app/controllers/contents_controller.rb, app/controllers/event_controller.rb, app/controllers/profiles_controller.rb, app/controllers/speaker_dashboard/speakers_controller.rb, app/controllers/speaker_dashboards_controller.rb, app/controllers/speakers_controller.rb, app/controllers/sponsor_dashboards/speakers_controller.rb, app/controllers/sponsor_dashboards/sponsor_dashboards_controller.rb, app/controllers/sponsor_dashboards/sponsor_profiles_controller.rb, app/controllers/talks_controller.rb, app/controllers/teams_controller.rb, app/controllers/timetable_controller.rb, app/helpers/application_helper.rb, spec/controllers/application_controller_spec.rb
1. Implements `current_user` with the same implementation as `set_current_user` <- This PR
2. Replace all `@current_user` ivar access with `current_user` method
3. Remove `set_current_user` method
We need to call the `set_current_user` method before using the `@current_user` variable. This can lead to mistakes.
So replace ivar to memoized `current_user` method call.
Once all changes are completed, `set_current_user` method will be removed, reducing the number of `before_action` callbacks.
This PR simply replaces the implementation with an equivalent one, so there are no impacts.
=> Refactor: Use `current_user` instead of `set_current_user` (1/3)

app/controllers/concerns/secured.rb, app/controllers/concerns/secured_admin.rb, app/controllers/concerns/secured_api.rb, app/controllers/concerns/secured_beta.rb, app/controllers/concerns/secured_speaker.rb, app/controllers/concerns/secured_sponsor.rb, app/controllers/event_controller.rb, app/controllers/proposals_controller.rb, app/controllers/speaker_dashboard/speakers_controller.rb
1. Implements `current_user` with the same implementation as `set_current_user`
* #2278
2. Replace all `@current_user` ivar access with `current_user` method
* #2279
3. Remove `set_current_user` method <- This PR
With the replacement of all `@current_user` ivar with `current_user` method, the `set_current_user` method has become redundant.
This PR removes the `set_current_user` method along with any codes that call it.
Since all `@current_user` ivar have already been replaced with `current_user` method call, there are no effects on functionality.
=> Refactor: Use `current_user` instead of `set_current_user` (3/3)

app/controllers/speaker_dashboards_controller.rb
ApplicationController has `set_speaker` method.
https://github.com/cloudnativedaysjp/dreamkast/blob/6c4b9071bf895dea2f8006184382ed39e1ef885a/app/controllers/application_controller.rb#L140-L144
SpeakerDashboardsController's method is
https://github.com/cloudnativedaysjp/dreamkast/blob/6c4b9071bf895dea2f8006184382ed39e1ef885a/app/controllers/speaker_dashboards_controller.rb#L21-L27
Only differences are related to setting @talks, so setting of `@talks` into the action and remove overriding.
NOTE: `set_conference` implementation is here.
https://github.com/cloudnativedaysjp/dreamkast/blob/6c4b9071bf895dea2f8006184382ed39e1ef885a/app/controllers/application_controller.rb#L128-L130 https://github.com/cloudnativedaysjp/dreamkast/blob/6c4b9071bf895dea2f8006184382ed39e1ef885a/app/controllers/applic …
=> Avoid overriding `set_speaker` method in SpeakerDashboardsController

app/controllers/api/v1/check_in_conferences_controller.rb, app/controllers/api/v1/check_in_talks_controller.rb, app/controllers/concerns/secured_public_api.rb, app/models/check_in_conference.rb, app/models/check_in_talk.rb, app/models/conference.rb, app/models/profile.rb, app/models/talk.rb, config/routes.rb, db/migrate/20240421052443_add_new_check_ins_tables.rb, db/schema.rb, schemas/swagger.yml, spec/rails_helper.rb, spec/requests/api/v1/check_in_conferences_create_spec.rb, spec/requests/api/v1/check_in_talks_create_spec.rb
- イベントとセッションそれぞれにチェックイン用のエンドポイントを追加しました
- UI側の実装を楽にするため追記型にして、同じ参加者でも何回でもチェックインできるようにしています。
=> チェックイン用のAPIエンドポイントを追加

app/controllers/profiles_controller.rb, app/javascript/stylesheets/_entry_sheet.scss, app/views/layouts/partial/_login_button.erb, app/views/profiles/view_qr.html.erb, config/routes.rb
ナビバーに受付用QRコードを表示する遷移を追加しました。
スマートフォン表示を前提にしています。
QRコードの表示サイズはスマートフォン表示時で横幅の50％にしていいますがこちらは随時調整可能です。
PCで開くことはないと思いますが、一応最低限表示できるようにCSSを分けています。
=> QRコードの表示画面を追加

app/javascript/stylesheets/_entry_sheet.scss, app/views/profiles/entry_sheet.html.erb, app/views/profiles/partial_entry_sheet/_up_left_cell.html.erb, app/views/profiles/partial_entry_sheet/_up_right_cell.html.erb
QRコードが小さく印刷すると読み取りができなかったので大きくした。それに伴いレイアウトも変更。
読み取り最優先の大きさにしたのでCNDSロゴは泣く泣く外した
=> エントリーシートのQRコード周りを調整

config/initializers/sentry.rb
- Sentry に `connect` という transaction が大量に送られてきて Sentry のディスクがいっぱいになる事象がたびたび起こっている
- 中身は、dreamkast から Sentry への HTTP リクエスト。200 OK で返っている
- ```json
{
// ...
"breadcrumbs": {
"values": [
{
"category": "net.http",
"data": {
"method": "PUT",
"status": 200,
"url": "[Filtered]"
},
"level": "info",
"message": "",
"timestamp": 1717554939.0,
"type": "info"
},
// ...
{
"category": "net.http",
"data": {
"method": "GET",
"status": 200,
"url": "[Filtered]"
},
"level": "info",
"message": "",
"timestamp": 1717554939.0,
"type": "info"
}
]
},
// ...
"title": "connect",
"transaction": "connect",
// ...
}
```
- こういう event が × 10 万件くらい一気に送られている
おそらく…
- dreamkast から Sentry に event や tansaction を送っている。この送る動作自体の transaction が生成されている
- 一連の `Net:HTTP.connect` 呼び出しが 1 つの transaction に溜め込まれている
- `traces_sample_rate …
=> Sentry への接続 transaction 自体は Sentry に送らない

app/javascript/packs/speaker_form.js
`Delete talk` ボタンクリック時にinput要素などからrequiredを消す処理がうまく動いていなかった
=> fix: セッション登録フォームでセッションを削除した後に登録・更新できない問題を修正

app/middlewares/dreamkast_exporter.rb
オブザーバビリティチームでtelegrafを廃止を進めています。その一環で、以前に https://github.com/cloudnativedaysjp/dreamkast/pull/2064 が https://github.com/cloudnativedaysjp/dreamkast-infra/blob/b5d51cfcf912e82fb583fd5d1dd8fcee15c7e289/manifests/infra/telegraf/base/configmap.yaml#L99-L102 を置き換えたように、このpull requestで https://github.com/cloudnativedaysjp/dreamkast-infra/blob/b5d51cfcf912e82fb583fd5d1dd8fcee15c7e289/manifests/infra/telegraf/base/configmap.yaml#L95-L98 を置き換えます。
計装されるメトリック (`curl http://localhost:3000/metrics | ag dreamkast_select_talks`) : 
```
TYPE dreamkast_select_talks gauge
dreamkast_select_talks{talk_id="1",conference_id="1",title="云々",talk_difficulty_name="初級者"} 1.0
…
dreamkast_select_talks{talk_id="803",conference_id="7",title="CM1",talk_difficulty_name=""} 803.0
…
```
実行される SQL
```
Talk Load (1.1ms) …
```
=> Talk一覧をPrometheusから取得する

Dockerfile
pull request を作ると以下がこんな https://github.com/cloudnativedaysjp/dreamkast/pull/2396/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557 な感じでコメントされるので、簡単に直せるものを直した。
```
6 warnings found (use docker --debug to expand):
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 17)
- SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ENV "AWS_ACCESS_KEY_ID") (line 34)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 40)
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 3)
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 10)
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 16)
```
確認方法 : 
`docker …
=> docker build --check の簡単なものを直す

app/middlewares/dreamkast_exporter.rb
GET /metrics で、`SELECT COUNT(*) FROM profiles WHERE profiles.conference_id = 1` と `SELECT COUNT(*) FROM talks WHERE talks.conference_id = 1` が Conference ごとに実行されている。
この差分で、以下のように Profile Count と Talk Count とにまとめられる。
```
Profile Count (0.9ms)  SELECT COUNT(*) AS `count_all`, `profiles`.`conference_id` AS `profiles_conference_id` FROM `profiles` GROUP BY `profiles`.`conference_id`
↳ app/middlewares/dreamkast_exporter.rb:88:in `dreamkast_registrants_count'
Conference Load (0.7ms)  SELECT `conferences`.* FROM `conferences`
↳ app/middlewares/dreamkast_exporter.rb:89:in `dreamkast_registrants_count'
Talk Count (0.8ms)  SELECT COUNT(*) AS `count_all`, `talks`.`conference_id` AS `talks_conference_id` FROM `talks` GROUP BY `talks`.`conference_id`
↳ app/middlewares/dreamkast_exporter.rb:98:in …
```
=> GET /metrics の n+1 を解消

app/controllers/speaker_invitation_accepts_controller.rb
If user doesn't logged in, current_user is nil, so error occurred. We don't use `@speaker` in view of invite, so delete it.
=> fix: undefined method `[]' for nil

Gemfile, Gemfile.lock, app/controllers/admin/stamp_rally_check_points_controller.rb, app/javascript/packs/controllers/index.js, app/javascript/packs/controllers/modal_controller.js, app/javascript/packs/controllers/sponsor_controller.js, app/javascript/packs/controllers/toast_controller.js, app/models/concerns/ulid_pk.rb, app/models/conference.rb, app/models/sponsor.rb, app/models/stamp_rally_check_point.rb, app/models/stamp_rally_check_point/type.rb, app/models/stamp_rally_check_point_booth.rb, app/models/stamp_rally_check_point_finish.rb, app/views/admin/_navigator.html.erb, app/views/admin/stamp_rally_check_points/_form.html.erb, app/views/admin/stamp_rally_check_points/_stamp_rally_check_point.html.erb, app/views/admin/stamp_rally_check_points/create.turbo_stream.erb, app/views/admin/stamp_rally_check_points/destroy.turbo_stream.erb, app/views/admin/stamp_rally_check_points/edit.html.erb, app/views/admin/stamp_rally_check_points/index.html.erb, app/views/admin/stamp_rally_check_points/new.html.erb, app/views/admin/stamp_rally_check_points/update.turbo_stream.erb, app/views/application/_flash.html.erb, app/views/layouts/_modal.html.erb, app/views/layouts/application.html.erb, config/routes.rb, db/fixtures/development/03_sponsors.rb, db/migrate/20241006001733_add_tables_for_stamp_rally_check_points.rb, db/schema.rb
Implement https://www.notion.so/pfem/34dbdb151f134b07808f27add4a7a1dc?pvs=4#ccb4f4e91fc94661ac016eeb97c28980
=> feat: manage stamp rally check points

app/controllers/admin/qr_code_for_stamp_rallies_controller.rb, app/controllers/admin/stamp_rally_check_points_controller.rb, app/controllers/application_controller.rb, app/models/qr_code_for_stamp_rally.rb, app/models/stamp_rally_check_point.rb, app/models/stamp_rally_check_point_booth.rb, app/models/stamp_rally_check_point_finish.rb, app/views/admin/qr_code_for_stamp_rallies/show.html.erb, app/views/admin/stamp_rally_check_points/_form.html.erb, app/views/admin/stamp_rally_check_points/_stamp_rally_check_point.html.erb, app/views/admin/stamp_rally_check_points/index.html.erb, app/views/layouts/application.html.erb, config/routes.rb, db/migrate/20241102104024_add_columns_to_stamp_raly_check_points.rb, db/schema.rb, spec/factories/stamp_rally_check_point_booth.rb, spec/factories/stamp_rally_check_point_finish.rb
https://www.notion.so/pfem/34dbdb151f134b07808f27add4a7a1dc?pvs=4#8f1028ad3a5f4439bda59c7db70b0eec
and, add name and desciription column to stamp rarry check point.
=> [feat] add qr code page to check in

config/initializers/sentry.rb
https://github.com/cloudnativedaysjp/dreamkast/pull/2324 で下げていたのを、戻す
下げた当時の問題は https://github.com/cloudnativedaysjp/dreamkast/pull/2342 で解決した
=> Sentry sampling_rate を 1% に上げる (戻す)

config/initializers/sentry.rb
> [!IMPORTANT]
> `DREAMKAST_NAMESPACE`を変更しないことによる暫定対応になります
`config.enabled_environments`に`dreamkast-prod-dk`を追加
=> fix: add config.enabled_environments

app/views/timetable/_timetable_cndw2024.html.erb, lib/tasks/add_talks_for_cndw2024_intermission.rake
2日目のクロージングの時間が前倒しになったけど、1日目との整合性を取りたい＆時刻の設定はそれほど重要ではないので気にせず18時からにする
=> CNDW2024のRaketaskを追加

lib/tasks/render_json_for_website.rake
Currently, we use json for data of talks and speakers.
```
#!/usr/bin/env bash
ABBR=cnds2024
export AWS_REGION=ap-northeast-1
TASK_ARN=$(aws ecs list-tasks --output text --cluster dreamkast-prod --service-name dreamkast --query "taskArns[0]")
aws ecs execute-command --interactive --cluster dreamkast-prod --task $TASK_ARN --container dreamkast --command "bundle exec rake util:render_json_for_website[$ABBR]"
aws ecs execute-command --interactive --cluster dreamkast-prod --task $TASK_ARN --container dreamkast --command "cat ${ABBR}_speakers.json" \
| gsed -z 's/\nThe Session Manager plugin was installed successfully\. Use the AWS CLI to start a session\.\n\n\nStarting session with SessionId: .*\n\[/\[/g' \
| gsed 's/^Exiting session with sessionId:.*$//g' \
> ./src/data/speakers/$ABBR.json …
```
=> chore: use json by website

app/controllers/check_in_conferences_controller.rb, app/controllers/profiles_controller.rb, app/models/profile.rb, app/views/check_in_conferences/new.html.erb, app/views/profiles/new.html.erb, config/routes.rb, spec/requests/check_in_conferences_spec.rb, spec/requests/profiles_spec.rb, webpack.config.js
- チェックイン情報を保持するテーブルをcheck_in_conferencesに統一
- check_in_conferencesUIからスキャンしてチェックインする時に使うテーブル
- ログインしていない時にいきなりauth0にリダイレクトするのではなく、ログインボタンを表示したページを挟むよう変更
- iPhoneでスキャンした時、未ログインの内部ブラウザで開いてしまうと困ることがあるため
- セルフチェックイン用のURLを `/:event_abbr/self_check_in` に変更
=> セルフチェックインの改修

app/middlewares/dreamkast_exporter.rb
- 参加者数の属性（オフライン/オンライン）をダッシュボードに出力するために必要なメトリクスを追加しました
- `stats_of_registrants`に値が入ると以下のようなメトリクスを出力するようになっています
```sh
dreamkast_stats_of_registrants_offline{conference_id="1"} 50.0
dreamkast_stats_of_registrants_offline{conference_id="2"} 50.0
dreamkast_stats_of_registrants_online{conference_id="1"} 50.0
dreamkast_stats_of_registrants_online{conference_id="2"} 60.0
```
=> Added Stats of Registrants metrics

.github/workflows/build-branch.yml, .github/workflows/build-tag.yml, .github/workflows/make-swagger-artifacts.yml, .github/workflows/reviewapp-cleanup.yml, .github/workflows/reviewapp.yml
* related PR: https://github.com/cloudnativedaysjp/reusable-workflows/pull/25
=> migrate aws-credential from access-key to using GitHub OIDC

app/controllers/admin/talks_controller.rb, spec/requests/admin/talks_spec.rb
ついでに、他の日にオンエアが残っている時にうまく動いていなかった問題も修正した
=> fix: セッションをオンエアに切り替えた際、他トラックのセッションが全てオンエアではなくなる問題を修正

app/models/profile.rb, app/views/profiles/_form.html.erb
- Added presence validation for participation in Profile model
- Updated participation radio buttons in the profile form to include required attribute and adjusted label styling
=> 参加方法の選択を必須項目にします

app/models/media_package_v2_origin_endpoint.rb
CloudFrontのキャッシュ有効期間を短くする。キャッシュポリシーは https://github.com/cloudnativedaysjp/terraform/pull/234 で作成済み。手元では前日同時間に流したデータが翌日混ざることはなかったが、本当にこれで直るのかはあまり自信がない…
=> fix: shorten cache life
