cloudnativedaysjp/dreamkast

Dockerfile, README.md, config/database.yml, config/webpacker.yml, docker-compose.yaml, entrypoint.sh
=> Add document how to setup auth0 keys

entrypoint.sh
=> 31 delete pid

Procfile, config/database.yml, docker-compose.yaml
Finished #2 
いったん最速で作るためにHerokuを使うことにした。
このPRではDB名が固定だったので環境変数で渡せるように変更しています。（HerokuのClearDB対応）
デプロイ時にdb:migrateとdb:seedを行うようにProcfileも設定。
https://dreamkast.herokuapp.com/   に立ち上がることを確認した
=> CD出来るように変更

app/views/home/show.html.erb
=> Add timetable button

app/views/layouts/application.html.erb
本番用Karteタグの追加。
localhost で設置してあってもとりあえずは問題無さそう。
（karte側でごちゃごちゃしてきてしまったら考えます。）
=> add karte tag

app.json, config/database.yml
PR投げたらHerokuでレビュー用のアプリがデプロイされるようにした。
PRページの↓↓にある This branch was successfully deployed から Show environments したらレビュー用アプリにアクセスできます。DBの自動でプロビジョニングされるようになってます。
=> Review apps対応

app/views/layouts/application.html.erb
karte 上でユーザを識別するためのユニークなIDを送付するように変更。
ちなみにCookieを削除しないかぎり、過去分もさかのぼってトラッキングの紐付けを行ってくれます。
1回呼べれば良いんですが、いまいちいい場所が見当たらず。
=> add user segmentation for karte

app/controllers/timetable_controller.rb, app/views/home/show.html.erb, app/views/layouts/application.html.erb, app/views/timetable/index.html.erb, config/routes.rb
=> rename timeline to timetable

app/assets/stylesheets/custom.css.erb, app/controllers/application_controller.rb, app/controllers/speakers_controller.rb, app/models/speaker.rb, app/views/speakers/_form.html.erb, app/views/speakers/index.html.erb, app/views/speakers/show.html.erb, app/views/talks/_show_modal.html.erb, config/environments/development.rb, config/routes.rb, db/migrate/20200704133202_create_active_storage_tables.active_storage.rb, db/schema.rb
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/71
=> スピーカーの画像表示に対応する

db/migrate/20200710134030_add_avatar_data_to_speaker.rb, db/schema.rb
ref: https://github.com/cloudnativedaysjp/dreamkast/pull/92
=> db:migrationが外部キー制約で失敗する問題を修正

app/controllers/admin_controller.rb, app/controllers/concerns/secured.rb, app/controllers/profiles_controller.rb, app/helpers/admin_helper.rb, app/views/admin/_message.html.erb, app/views/admin/accesslog.html.erb, app/views/admin/show.html.erb, app/views/admin/speakers.html.erb, app/views/admin/talks.html.erb, app/views/admin/users.erb, config/routes.rb
Auth0ユーザーに設定されているRoleに応じてアクセス制御が出来ること
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/64
=> Roleによるアクセス制御を実装

app/controllers/concerns/secured.rb, app/controllers/speakers_controller.rb, app/controllers/timetable_controller.rb, app/views/layouts/_event_header.html.erb, app/views/timetable/_form.html.erb, app/views/timetable/_timetable.html.erb, app/views/timetable/index.html.erb, config/routes.rb
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/97
=> ログインしていない時でもタイムテーブルとスピーカーが見えて欲しい

app/controllers/timetable_controller.rb, app/views/timetable/_timetable.html.erb
影響があるほど多いか？というとそうでもない気もするけど、あらかじめ減らせるだけ減らしておく
=> タイムテーブル表示時のクエリ発行数を減らす

Gemfile, Gemfile.lock, config/routes.rb, spec/controllers/profiles/talks_controller_spec.rb, spec/factories/profiles.rb, spec/rails_helper.rb
`get 'talks', to: 'talks#show'` のルートは使われてない気がするのでついでに削除
=> add test: Profiles::TalksController

config/routes.rb, spec/requests/auth_spec.rb
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/108
=> /:event/auth/auth0 へのリクエストは /auth/auth0 にリダイレクトする

spec/factories/conference_days.rb, spec/factories/conferences.rb, spec/factories/talk_categories.rb, spec/factories/talk_difficulties.rb, spec/factories/talks.rb, spec/requests/timetable_spec.rb
* ログインしていない場合
* ログインしている場合
についてリクエストテストを追加
=> add test: TimetableController

app/controllers/admin_controller.rb, app/controllers/application_controller.rb, app/views/admin/_message.html.erb, app/views/admin/accesslog.html.erb, app/views/admin/show.html.erb, app/views/admin/talks.html.erb, app/views/admin/users.erb, app/views/errors/error_403.html.erb, app/views/layouts/_event_header.html.erb, spec/requests/admin_spec.rb, spec/requests/profiles/talks_spec.rb, spec/requests/timetable_spec.rb
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/118
=> /admin以下のページはadmin roleを持つユーザーのみアクセス可能にする

app/views/profiles/_form.html.erb
=> Update IBM privacy statement

app/views/layouts/_event_header.html.erb, app/views/layouts/_karte.html.erb, app/views/layouts/application.html.erb
関連PR
https://github.com/cloudnativedaysjp/dreamkast/pull/80
=> track時に利用するイベント情報が文字列になっていない問題の修正

app/helpers/application_helper.rb, app/javascript/packs/application.js, app/javascript/packs/message_box.js, app/javascript/packs/timetable.js, app/javascript/stylesheets/_message_box.scss, app/javascript/stylesheets/_timetable.scss, app/javascript/stylesheets/application.scss, app/views/layouts/application.html.erb, app/views/profiles/edit.html.erb, app/views/profiles/new.html.erb, app/views/profiles/talks/show.html.erb, app/views/speakers/index.html.erb, app/views/timetable/index.html.erb
#135 を解消するのが目的だったけど、結果として `@message_box` にテキストを入れるだけで良い感じに喋ってくれる最高の仕組みが出来ました
=> Improve navigation

README.md, entrypoint.sh
=> appサービスはないのでdb:migrateは手元で実行する必要がある

app/javascript/stylesheets/_timetable.scss, app/views/layouts/_event_header.html.erb, app/views/talks/_show_modal.html.erb
=> Apply review 2

app/controllers/auth0_controller.rb, app/controllers/concerns/secured.rb, app/controllers/event_controller.rb, app/views/layouts/_event_header.html.erb
=> ログイン後のプライバシーポリシー、CoCからナビゲーションがおかしくなる件を修正

db/seeds.rb
=> Production Envでもtrackを入れるように変更

app/views/dashboard/show.html.erb, db/seeds.rb
=> /dashboardのアクセスがこける件を修正

app/controllers/application_controller.rb, app/middlewares/rescue_from_invalid_authenticity_token.rb, app/views/errors/error_403.html.erb, app/views/errors/error_500.html.erb, config/application.rb, config/initializers/auth0.rb, config/initializers/rescue_from_invalid_authenticity_token.rb
=> エラーハンドリング周りを改善

app/controllers/admin_controller.rb, app/views/admin/_navigator.html.erb, app/views/admin/statistics.erb, config/routes.rb, db/speakers.csv
/admin/statistics からCSVをエクスポート可能にした
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/212
=> 申込者数とセッション登録者数をCSVファイルでエクスポートできるようにする

app/models/speaker.rb, app/views/speakers/index.html.erb, app/views/talks/_show_modal.html.erb, app/views/talks/show.html.erb
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/209
=> スピーカーのtwitter_idやgithub_idが空文字列ではなくNULLの場合表示されてしまう問題を修正

app/helpers/application_helper.rb, app/views/layouts/application.html.erb, db/schema.rb
Addresses https://github.com/cloudnativedaysjp/dreamkast/issues/203
=> Implement ogp and twitter card

app/javascript/stylesheets/_tracks.scss, app/views/tracks/index.html.erb
Fix #240 
配信ページにDiscord Widgetを埋め込んだ
=> Add discord widget

app/controllers/admin/sponsors_controller.rb, app/forms/sponsor_form.rb, app/models/sponsor.rb, app/models/sponsor_attachment_zoom.rb, app/views/admin/sponsors/_form.html.erb, app/views/booths/_booth.html.erb
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/4
=> スポンサーブースにZoomなどへのリンクを追加できるようにする

app/forms/sponsor_form.rb
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/256
=> ブースのテキスト情報が初回入力時に保存されない問題を修正

Gemfile, Gemfile.lock, app/views/booths/_booth.html.erb
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/258
=> URLをリンクに自動変換する

app/views/booths/_booth.html.erb
https://github.com/cloudnativedaysjp/dreamkast/issues/258
=> sponsor.description内のURLもリンクにする

app/views/contents/index.html.erb
upstream training のフォームを閉じるための変更。
8/31 18:00 に閉じる予定。
=> close upstream training application

app/controllers/event_controller.rb, app/views/event/show.html.erb
クエリの発行回数を減らします
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/275
=> event#showの高速化

Gemfile, Gemfile.lock, config/environments/development.rb
=> Add bullet gem to detect n+1 queries

app/controllers/timetable_controller.rb
https://github.com/cloudnativedaysjp/dreamkast/issues/277
=> reduce N+1 on /timetables

app/controllers/dashboard_controller.rb
Conferenceに関連付けられたTalkは使っていないので削除
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/279
=> talks related conference isn't used

db/fixtures/production/seeds.rb
=> Red HatをBoothスポンサーに

app/javascript/packs/tracks/track_control.js
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/288
=> OnAir状態のトークがない場合はCMを流す

app/controllers/admin/tracks_controller.rb, app/javascript/packs/application.js, app/views/admin/tracks/_tracks_nav.html.erb, app/views/admin/tracks/index.html.erb, app/views/admin/tracks/update_tracks.js.erb
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/288
=> OnAirコントロールはAjaxでやる

app/controllers/admin/attachments_controller.rb, app/controllers/attachments_controller.rb, app/views/booths/_booth.html.erb, config/routes.rb
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/8
=> PDFダウンロードのロギング

app/controllers/concerns/logging.rb, app/models/access_log.rb, db/migrate/20200907030040_add_profile_id_column_to_access_log.rb
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/8
=> add profile_id to access_log

app/controllers/tracks_controller.rb, app/javascript/packs/tracks/track_control.js, app/views/tracks/blank.html.erb
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/316
=> sli.doのidがない場合はsli.doを表示しない

app/views/talks/show.html.erb
なんか個別動画が表示されないと思ったら・・・はずかしい・・・
=> Fix talks view

app/views/booths/_booth.html.erb
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/327
=> スポンサーの人と話せるリンクを画面上部にも設置

app/views/talks/show.html.erb, yarn.lock
=> Fix document link

db/fixtures/seeds.rb
=> Change default status to closed

lib/tasks/relate_speaker_to_cndt2020_if_conference_id_is_nil.rake
speakerのconference_idも変更しないとだった。
https://github.com/cloudnativedaysjp/dreamkast/issues/348
=> add rake task: update speakers that don't have conference_id

app/views/layouts/_event_header.html.erb
=> 一時的にイベントがCNDT2020の場合のみメニューを表示するよう変更

app/controllers/application_controller.rb, app/controllers/speaker_dashboard/speakers_controller.rb, app/controllers/speaker_dashboards_controller.rb, app/models/conference.rb, app/models/talk.rb, app/models/talk_time.rb, app/policies/speaker_policy.rb, app/views/speaker_dashboard/speakers/_form.html.erb, app/views/speaker_dashboard/speakers/_talk_fields.html.erb, app/views/speaker_dashboard/speakers/new.html.erb, app/views/speaker_dashboards/show.html.erb, db/fixtures/development/seeds.rb, db/fixtures/production/seeds.rb, db/migrate/20201224094247_create_talk_times.rb, db/schema.rb, spec/factories/conferences.rb, spec/factories/speakers.rb, spec/factories/talk_times.rb, spec/models/talk_time_spec.rb, spec/requests/event_spec.rb, spec/requests/speaker_dashboard/speakers_spec.rb, spec/requests/speaker_dashboard_spec.rb
* トークに以下を追加
　* 技術領域
　* セッション時間
* 必須項目の制御を有効にした
* プレイスホルダを追加
https://github.com/cloudnativedaysjp/dreamkast/pull/357 の後にマージすること
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/358
=> エントリーフォームを修正

app/forms/speaker_form.rb, app/javascript/packs/speaker_form.js, app/views/speaker_dashboard/speakers/_form.html.erb, app/views/speaker_dashboard/speakers/_talk_fields.html.erb, app/views/speaker_dashboards/show.html.erb, db/fixtures/development/seeds.rb
https://github.com/cloudnativedaysjp/dreamkast/issues/362 の修正
=> エントリーフォームで、セッション概要をDeleteすると登録ボタンが作動しなくなる問題の修正

app/controllers/talks_controller.rb, app/forms/speaker_form.rb, app/models/talk.rb, app/views/layouts/_event_header.html.erb, app/views/speaker_dashboards/show.html.erb, app/views/talks/index.html.erb, app/views/talks/partial_show/_col_main_pane.html.erb, app/views/talks/partial_show/_col_speaker.html.erb, app/views/talks/partial_show/_col_speaker_avatar.html.erb, app/views/talks/partial_show/_col_sub_pane.html.erb, app/views/talks/partial_show/_col_talk_category_block.html.erb, app/views/talks/partial_show/_facebook_share_button.html.erb, app/views/talks/partial_show/_row_document_url.html.erb, app/views/talks/partial_show/_talk_video_block.html.erb, app/views/talks/partial_show/_twitter_share_button.html.erb, app/views/talks/show.html.erb
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/378
=> CNDO2021の各セッションを一覧表示&個別ページ表示可能にする

app/views/talks/partial_show/_col_main_pane.html.erb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/398
=> トーク概要は改行を反映したい

app/controllers/admin/talks_controller.rb, app/views/admin/talks/index.html.erb
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/395
=> CNDO2021のadmin/talksで保存するとその後404になる問題を修正

app/controllers/talks_controller.rb, spec/factories/conferences.rb, spec/requests/talks_spec.rb
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/399
=> 他イベントのトークがURL直打ちで見えてしまう

Gemfile, Gemfile.lock, app/controllers/api/v1/conferences_controller.rb, app/views/api/v1/conferences/show.json.jbuilder, config/routes.rb, schemas/swagger.yml, spec/factories/conferences.rb, spec/rails_helper.rb, spec/requests/api/v1/event_show_spec.rb
とりあえずswagger.ymlはコピーしてやる
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/382
=> イベント参照用のAPIを追加&OpenAPI使ったテストを追加

app/controllers/api/v1/talks_controller.rb, app/models/talk.rb, app/views/api/v1/talks/index.json.jbuilder, config/routes.rb, schemas/swagger.yml, spec/requests/api/v1/talk_index_spec.rb
schema更新: https://github.com/cloudnativedaysjp/dreamkast-api-docs/pull/5
=> add api: /api/v1/talks

app/controllers/api/v1/talks_controller.rb, app/controllers/api/v1/tracks_controller.rb, app/models/track.rb, app/views/api/v1/talks/show.json.jbuilder, app/views/api/v1/tracks/index.json.jbuilder, app/views/api/v1/tracks/show.json.jbuilder, config/routes.rb, schemas/swagger.yml, spec/requests/api/v1/talk_show_spec.rb, spec/requests/api/v1/track_index_spec.rb, spec/requests/api/v1/track_show_spec.rb
ref: https://github.com/cloudnativedaysjp/dreamkast-api-docs/pull/6
=> add api: show talk, index track, show track

app/views/talks/partial_show/_col_speaker.html.erb
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/418
=> talk画面のスピーカープロフィールの改行を有効にする

.github/workflows/gc.yaml, .github/workflows/gitops.yml
=> Fix GitOps

db/fixtures/production/seeds.rb
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/433
=> 状態を管理するフィールドをseedに含めていると、promote毎に上書きされてしまうので消す

app/views/tracks/waiting.html.erb
difficulty無くて死ぬ問題がdashboardにもあった
=> Fix dashbaord

app/controllers/admin/speakers_controller.rb, app/helpers/speakers_helper.rb, app/views/admin/speakers/edit.html.erb, app/views/speaker_dashboard/speakers/_form.html.erb, app/views/speaker_dashboard/speakers/_talk_fields.html.erb, db/csv/cndo2021/speakers.csv
=> adminページからはスピーカーとトークを編集可能にする

.github/workflows/ci.yaml, .github/workflows/gc.yaml, .github/workflows/gitops.yml
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/444
=> デフォルトブランチ名をmainに変更する

.github/workflows/ci.yaml
=> Avoid building dreamkast image when running CI

app/controllers/speaker_dashboard/videos_controller.rb, app/mailers/speaker_mailer.rb
新規送信時、Toが空になっていた問題を修正 (SpeakerモデルとProfileモデルが異なるせい)
=> Fix speakermailer

app/controllers/api/v1/chat_messages_controller.rb, app/controllers/api/v1/sponsors_controller.rb, app/controllers/api/v1/talks_controller.rb, app/controllers/api/v1/tracks_controller.rb, app/views/api/v1/chat_messages/index.json.jbuilder, app/views/api/v1/sponsors/index.json.jbuilder, schemas/swagger.yml, spec/requests/api/v1/sponsor_index_spec.rb, spec/requests/api/v1/talk_index_spec.rb, spec/requests/api/v1/track_index_spec.rb
https://github.com/cloudnativedaysjp/dreamkast-api-docs/pull/13
https://github.com/cloudnativedaysjp/dreamkast-api-docs/issues/12
=> Ｅventで絞り込む際、abbrを使うように統一する

app/views/tracks/waiting.html.erb
=> Fix dashboard

app/controllers/api/v1/talks_controller.rb, schemas/swagger.yml, spec/factories/talks.rb, spec/requests/api/v1/talk_index_spec.rb
=> Support trackId param

.github/workflows/gitops.yml, README.md, config/default.conf, docker-compose.yaml
UIとLBをdocker-composeで上げられるようにした
=> Add UI and LB for local development

app/views/api/v1/sponsors/index.json.jbuilder
欲しいURLは実際に画像が出るURLのほうなのでヘルパーを通すようにした
=> Fix logo_image url

app/views/tracks/waiting.html.erb
ちなみに分岐入れてないのでCNDT2020のほうも変わっちゃうけど、最新のイベント告知って意味もあるしこれでいいかなって
=> Waiting画面のMovieを変更

app/controllers/admin_controller.rb, app/views/admin/statistics.erb
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/488
=> export_statisticsが複数イベント化にまだ対応していなかった

app/controllers/admin/profiles_controller.rb, app/models/profile.rb, app/views/admin/users.erb, config/routes.rb
id, email, last_name, first_nameをCSV形式でエクスポートする機能をadminに追加。
https://github.com/cloudnativedaysjp/dreamkast/issues/489
=> 参加者のエクスポート機能を追加

app/views/admin/talks/index.html.erb
https://github.com/cloudnativedaysjp/dreamkast/issues/491
=> ビデオファイルをアップロード済みの場合はURLを表示する

app/channels/chat_channel.rb, app/controllers/api/v1/chat_messages_controller.rb, app/jobs/chat_message_broadcast_job.rb, app/views/api/v1/chat_messages/index.json.jbuilder, chat_message.json, config/application.rb, config/default.conf, config/environments/development.rb, db/fixtures/development/seeds.rb, db/migrate/20210216095643_update_columns_to_chat_messages.rb, db/schema.rb, schemas/swagger.yml, yarn.lock
https://github.com/cloudnativedaysjp/dreamkast/issues/374
=> UIとあわせてチャット機能を実装するためにあれこれ修正

app/models/talk.rb
https://github.com/cloudnativedaysjp/dreamkast/pull/504 のコードが間違っていた…
=> speakersじゃなくてtalks_speakersから配列を作ろうとしていた

app/controllers/api/v1/chat_messages_controller.rb, app/jobs/chat_message_broadcast_job.rb, app/models/chat_message.rb, app/views/api/v1/chat_messages/index.json.jbuilder, db/fixtures/development/seeds.rb, db/migrate/20210221071413_add_columns_to_chat_messages.rb, db/schema.rb, schemas/swagger.yml
チャットメッセージに情報を追加
- profile id
- speaker id
- メッセージがchatかqaか
UI: https://github.com/cloudnativedaysjp/dreamkast-ui/pull/47
API: https://github.com/cloudnativedaysjp/dreamkast-api-docs/pull/17
=> Refine chat

.github/workflows/gitops-dev.yml, .github/workflows/gitops-prd.yml
=> modify GitHub Actions

app/jobs/chat_message_broadcast_job.rb
https://github.com/cloudnativedaysjp/dreamkast-ui/pull/51
=> ActionCableでメッセージを送る際にreplyToを送らないといけない

app/models/talk.rb
videoのidじゃなくてvideoのvideo_idを使わないといけなかった
=> Fix video_id

app/views/api/v1/tracks/index.json.jbuilder, db/fixtures/development/seeds.rb, db/migrate/20210224142606_update_columns_to_tracks.rb, db/schema.rb, spec/factories/tracks.rb
- tracksのmovie_urlをvideo_idに変更
- trackにvideo_platformを追加（videosとそろえておく）
=> Tracks APIのvideoIdはライブ放送のIDを返して、ライブとアーカイブを切り替えられる用にしたい

app/views/layouts/_event_header.html.erb
- ヘッダにダッシュボードへのリンクを追加
- 右上のメニューからスピーカーダッシュボードへ移動できるようリンクを追加
=> ダッシュボードなどへの導線を追加

app/controllers/admin/conferences_controller.rb, app/javascript/packs/tracks/waiting_channel.js
fix https://github.com/cloudnativedaysjp/dreamkast/issues/540
=> イベントをオープンした時のリダイレクト先を更新

config/environments/production.rb
なんかデフォルトで全環境debugらしい。
fix https://github.com/cloudnativedaysjp/dreamkast/issues/541
=> production envではdebugログは出力しない

app/jobs/chat_message_broadcast_job.rb, app/views/api/v1/chat_messages/index.json.jbuilder, app/views/api/v1/talks/index.json.jbuilder, app/views/api/v1/talks/show.json.jbuilder, schemas/swagger.yml
https://github.com/cloudnativedaysjp/dreamkast-ui/issues/76
=> 登壇者のチャットメッセージを強調表示する

app/controllers/api/v1/booths_controller.rb, app/views/api/v1/booths/show.json.jbuilder, app/views/api/v1/sponsors/index.json.jbuilder, config/routes.rb, schemas/swagger.yml
ブースをUIで表示するように変更するので、ブース情報を返すAPIを追加する
API: https://github.com/cloudnativedaysjp/dreamkast-api-docs/pull/21
=> ブース情報を返すAPIを追加

db/fixtures/development/seeds.rb, db/fixtures/production/seeds.rb
=> Make pre-event internal

app/views/layouts/_analytics.html.erb, app/views/layouts/application.html.erb
=> Add google analytics tag

app/models/booth.rb, app/models/sponsor.rb, app/views/api/v1/booths/show.json.jbuilder, app/views/api/v1/sponsors/index.json.jbuilder, schemas/swagger.yml
- ブースがOpenかどうかも返す
- Attachmentがあるかどうか判定する
=> スポンサーとブースのAPIを更新

app/models/booth.rb, app/models/sponsor.rb, app/views/api/v1/booths/show.json.jbuilder, app/views/api/v1/sponsors/index.json.jbuilder, schemas/swagger.yml
Reverts cloudnativedaysjp/dreamkast#561
=> Revert "スポンサーとブースのAPIを更新"

.github/workflows/ci.yaml, .github/workflows/gc.yaml, .github/workflows/gitops-dev.yml, .github/workflows/release.yml
調べた限り GitHub API だと PullRequest 作成と label 付与を同時に出来無さそうだったので、 PR title で From bot であるかどうかを判別するようにしました
参考: https://github.com/cloudnativedaysjp/dreamkast-ui/pull/105
=> release用PRであることを判別する要素を label から title に変更

app/controllers/api/v1/chat_messages_controller.rb, app/controllers/api/v1/profiles_controller.rb, app/controllers/concerns/secured_api.rb, app/models/chat_message.rb, app/policies/chat_message_policy.rb, app/views/api/v1/profiles/my_profile.json.jbuilder, config/routes.rb, db/schema.rb, schemas/swagger.yml, spec/factories/chat_message.rb, spec/factories/profiles.rb, spec/requests/api/v1/chat_message_update_spec.rb, spec/requests/timetable_spec.rb
https://github.com/cloudnativedaysjp/dreamkast-api-docs/pull/23 に従ってAPIを追加
https://github.com/cloudnativedaysjp/dreamkast-ui/issues/71
=> チャットメッセージの削除のためのAPIを実装

app/views/admin/tracks/_tracks_nav.html.erb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/577
=> talkのstart_time/end_timeがNULLでもエラーにならないようにする

app/controllers/speaker_dashboard/speakers_controller.rb, app/views/speaker_dashboard/speakers/_talk_fields.html.erb, app/views/speaker_dashboards/show.html.erb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/576
=> 資料URLを追加できるようにする

db/fixtures/development/seeds.rb, db/fixtures/production/seeds.rb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/596
=> remove NewRelic from Booth Sponsors

app/views/layouts/application.html.erb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/585
=> 画面右下のマークはCNDO2021では表示しない

Dockerfile, Gemfile, Gemfile.lock, config/initializers/shrine.rb, config/routes.rb, entrypoint.sh
https://github.com/cloudnativedaysjp/dreamkast/issues/587
=> container build時にassets:precompileする

config/environments/production.rb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/588
=> INFOログの量が多いのでproductionではWARNに変更

docker-compose.yaml
Fix https://github.com/cloudnativedaysjp/dreamkast/issues/615
=> move migrate to compose from entrypoint

app/models/conference.rb, app/views/talks/partial_show/_col_main_pane.html.erb, spec/factories/conferences.rb, spec/requests/talks_spec.rb
https://github.com/cloudnativedaysjp/dreamkast/issues/628
=> イベントのステータスにArchivedを追加して、Archivedの場合はログインしなくてもビデオが見えるようにする

app/javascript/stylesheets/_admin.scss, app/views/admin/_layout.html.erb, app/views/admin/_nav_item.html.erb, app/views/admin/_navigator.html.erb, app/views/admin/accesslog.html.erb, app/views/admin/announcements/edit.html.erb, app/views/admin/announcements/index.html.erb, app/views/admin/announcements/new.html.erb, app/views/admin/booths/index.html.erb, app/views/admin/conferences/edit.html.erb, app/views/admin/debug.html.erb, app/views/admin/show.html.erb, app/views/admin/speakers/edit.html.erb, app/views/admin/speakers/index.html.erb, app/views/admin/sponsors/edit.html.erb, app/views/admin/sponsors/index.html.erb, app/views/admin/sponsors/show.html.erb, app/views/admin/statistics.erb, app/views/admin/talks/index.html.erb, app/views/admin/timetables/index.html.erb, app/views/admin/timetables/preview.html.erb, app/views/admin/tracks/index.html.erb, app/views/admin/users.erb, package-lock.json, package.json
adminのメニューの数が増えてきてきついのでサイドバーに移動します
adminのcontrainerも幅を広げて表示できる情報を増やせるようにした。
サイドバーは https://bootstrapious.com/p/bootstrap-sidebar を参考にした
=> adminのメニューをサイドバーに移動する

.github/workflows/gc.yaml, .github/workflows/gitops-dev.yml, .github/workflows/gitops-prd.yml, .github/workflows/gitops-stg.yml, .github/workflows/release.yml
cloudnativedaysjpにDreamkastReviewAppというGithubAppsを用意して、トークンをそこから取得するようにしました。これで個人のPersonalAccessTokenを使わなくてOKになる。 Secretとして `APP_ID` と `PRIVATE_KEY` を登録済みです。
=> Get token from GitHub app

app/forms/speaker_form.rb
c.f. https://github.com/cloudnativedaysjp/dreamkast/pull/680
=> additional_documentが保存されていなかった

app/views/talks/index.html.erb, app/views/talks/partial_show/_col_talk_category_block.html.erb
=> Fix permalink and session list

app/javascript/stylesheets/cicd2021/_cicd2021.scss, app/views/event/coc.html.erb, app/views/event/privacy.html.erb, app/views/speaker_dashboard/speakers/_form.html.erb, app/views/speaker_dashboard/speakers/_talk_fields.html.erb, app/views/speaker_dashboards/show.html.erb, app/views/talks/index.html.erb, app/views/talks/show.html.erb, db/fixtures/development/seeds.rb, db/fixtures/production/seeds.rb
=> Fix many things

app/models/chat_message.rb, app/models/profile.rb, spec/factories/conferences.rb, spec/factories/profiles.rb, spec/factories/speakers.rb, spec/factories/tracks.rb, spec/models/talk_spec.rb, spec/requests/admin/speakers_spec.rb, spec/requests/admin/talks_spec.rb, spec/requests/admin_spec.rb, spec/requests/api/v1/chat_message_update_spec.rb, spec/requests/api/v1/event_show_spec.rb, spec/requests/api/v1/sponsor_index_spec.rb, spec/requests/api/v1/talk_index_spec.rb, spec/requests/api/v1/talk_show_spec.rb, spec/requests/api/v1/track_index_spec.rb, spec/requests/api/v1/track_show_spec.rb, spec/requests/contents_spec.rb, spec/requests/event_spec.rb, spec/requests/profiles_spec.rb, spec/requests/speaker_dashboard/speakers_edit_spec.rb, spec/requests/speaker_dashboard/speakers_new_spec.rb, spec/requests/speaker_dashboard_spec.rb, spec/requests/talks_spec.rb, spec/requests/timetable_spec.rb, spec/requests/tracks_spec.rb
https://github.com/cloudnativedaysjp/dreamkast/pull/704 のテストを書きやすくするためリファクタリングしました
主には
- traitで重複を少なくした
- Conferenceのstatusでテストケースを分けた
などを変更
=> FactoryBot周りのリファクタリング

app/controllers/admin/talks_controller.rb
- 全ての項目を出力するようにする
- UTF-8に変更（これ変えてよかったけな）
fix https://github.com/cloudnativedaysjp/dreamkast/issues/750
=> refine talk export feature

app/controllers/admin/talks_controller.rb, app/models/talk.rb
- urlのエクスポートは今はできないのに間違えてコミットしてしまっていた
- twitter idをエクスポートできるようにした
- proposal_itemsをrowに追加する時、型名が入ってしまっていた
=> Talkのエクスポート修正

app/controllers/admin/proposals_controller.rb, app/controllers/admin/talks_controller.rb, app/models/talk.rb, app/views/admin/proposals/index.html.erb
admin>talksからエクスポートするとacceptedなもののみエクスポートされる。proposalは全てエクスポートしたいので、admin>proposal側からエクスポートできるようにする。
=> Proposalのエクスポート機能修正

lib/tasks/post_number_of_registrants_to_slack.rake
=> 参加者登録数の昨日との差分計算がおかしい問題を修正

app/views/contents/cicd2021_hands_on.html.erb
すみません:bow:
ケアレスミスがありまして、Google/クリエーションラインハンズオンに正しくリンクされていなかったので、修正しました:bow:
※プルリクの出し方はこんな感じでよろしいでしょうか…？
=> Correct link tag to Google Handson

app/controllers/application_controller.rb, app/views/event/partial/_speaker_entry_button.html.erb, app/views/layouts/_event_header.html.erb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/782
=> conferenceがregisteredかつspeaker_entry_disabledの時でも、既にスピーカーの場合はスピーカーダッシュボードへの導線を表示する

app/views/contents/cicd2021_hands_on.html.erb
実行委員ハンズオン、定員に達したため、満員締切の旨掲載しました
=> Close application to committee's hands-on

app/views/tracks/index.html.erb, app/views/tracks/waiting.html.erb
Fix #781 
UI側は https://github.com/cloudnativedaysjp/dreamkast-ui/issues/154 のほうで対応
=> Replace discord to oVice

app/views/event/partial/_speaker_entry_button.html.erb
=> Display deadline for CFP

app/controllers/admin/conferences_controller.rb, app/controllers/home_controller.rb, app/forms/conference_form.rb, app/helpers/home_helper.rb, app/javascript/stylesheets/_global.scss, app/models/conference.rb, app/views/admin/conferences/_form.html.erb, app/views/home/show.html.erb, app/views/layouts/application.html.erb, db/fixtures/development/00_seeds.rb, db/migrate/20210829032135_add_conference_brief.rb, db/schema.rb
Fix #756 
フッターにリンクを追加
ついでにDkのルートのデザインを大きく変えた
=> Add links for other events on footer

app/views/talks/partial_show/_col_other_talks.erb
=> Show only accepted talks

app/javascript/packs/speaker_form.js, app/views/admin/announcements/index.html.erb, app/views/admin/conferences/_form.html.erb, app/views/admin/proposals/index.html.erb, app/views/admin/show.html.erb, app/views/admin/sponsors/show.html.erb, app/views/admin/talks/index.html.erb, app/views/speaker_dashboard/speakers/_talk_fields.html.erb
クリックできるボタン(リンク) がそれと分かりづらかったので、ボタンのCSSを適用
=> Modify button design

db/fixtures/development/03_sponsors.rb, db/fixtures/production/03_sponsors.rb
=> Add sponsor 20210915

app/models/talk.rb
=> Add company name into csv

app/controllers/sponsor_dashboards/sponsor_profiles_controller.rb, app/policies/sponsor_profile_policy.rb, app/views/speaker_dashboard/speakers/_form.html.erb, app/views/sponsor_dashboards/sponsor_dashboards/_dashboard.html.erb, app/views/sponsor_dashboards/sponsor_profiles/_form.html.erb, app/views/sponsor_dashboards/sponsor_profiles/edit.html.erb, app/views/sponsor_dashboards/sponsor_profiles/new.html.erb, spec/requests/sponsor_dashboards/sponsor_profiles/sponsor_profiles_new_spec.rb
https://github.com/cloudnativedaysjp/dreamkast/issues/840
=> スポンサーの場合はCFP終了後でも登録可能にする & スポンサー担当者名の更新をサポート

db/fixtures/development/03_sponsors.rb, db/fixtures/production/03_sponsors.rb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/855
=> add sponsors

app/controllers/admin/admin_profiles_controller.rb, app/controllers/admin/announcements_controller.rb, app/controllers/admin/attachments_controller.rb, app/controllers/admin/booths_controller.rb, app/controllers/admin/chats_controller.rb, app/controllers/admin/conferences_controller.rb, app/controllers/admin/links_controller.rb, app/controllers/admin/profiles_controller.rb, app/controllers/admin/proposals_controller.rb, app/controllers/admin/speakers_controller.rb, app/controllers/admin/sponsors_controller.rb, app/controllers/admin/talks_controller.rb, app/controllers/admin/timetables_controller.rb, app/controllers/admin/tracks_controller.rb, app/controllers/admin/video_registrations_controller.rb, app/controllers/admin/videos_controller.rb, app/controllers/admin_controller.rb, app/controllers/concerns/secured_admin.rb, app/models/admin_profile.rb, app/views/admin/_navigator.html.erb, app/views/admin/admin_profiles/edit.html.erb, config/routes.rb, db/migrate/20210911075455_delete_date_column_from_talks.rb, db/migrate/20210921044345_create_admin_profiles.rb, db/schema.rb
- このPRではRBACはやらず、従来のAuth0のRoleを使用
- AdminProfileの各フィールドは https://github.com/cloudnativedaysjp/dreamkast/issues/745 で使用予定
fix https://github.com/cloudnativedaysjp/dreamkast/issues/639
=> 一般参加者と運営メンバーを分離する

app/views/event/partial/_speaker_entry_button.html.erb
条件間違っていてCFP締め切り表示が常に出ちゃっていた。
どっちにせよもう要らないので消す
=> Remove CFP text

app/views/timetable/_timetable_cndt2021.html.erb, db/fixtures/development/00_seeds.rb, db/fixtures/production/00_seeds.rb
=> Fix start time

db/fixtures/development/00_seeds.rb, db/fixtures/production/00_seeds.rb
=> Change endtime

app/models/live_stream_media_live.rb
=> std/prdのcloudfront domainを追加

app/controllers/api/v1/tracks_controller.rb, app/models/live_stream_ivs.rb, app/models/viewer_count.rb, app/views/api/v1/tracks/viewer_count.json.jbuilder, config/default.conf, config/routes.rb, db/migrate/20211030082839_create_viewer_counts.rb, db/schema.rb, lib/tasks/get_and_save_current_attendees.rake, schemas/swagger.yml, spec/factories/talks.rb, spec/factories/tracks.rb, spec/factories/viewer_counts.rb, spec/models/viewer_count_spec.rb, spec/requests/api/v1/track_viewer_count_spec.rb
Fix #831 
こちらも併せてれびゅーよろ
https://github.com/cloudnativedaysjp/dreamkast-api-docs/pull/27/
=> 視聴者数記録とAPIの実装

app/models/live_stream_ivs.rb, app/views/admin/live_stream_ivs/index.html.erb
admin/ivsに以下を表示するように変更。ついでにMediaLiveのidも表示する。
- id
- ingest url
- playback url
=> IVS Channel 情報を多めに表示する

app/controllers/application_controller.rb, app/views/layouts/application.html.erb
=> set noindex except for production

app/models/conference_day.rb, app/views/profile_mailer/registered.text.erb, spec/factories/conference_days.rb, spec/factories/conferences.rb, spec/mailers/profile_mailer_spec.rb, spec/requests/timetable_spec.rb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/1053
=> 参加登録をした時に送られるメールのハードコードを消す

spec/controllers/talks_controller/display_video_spec.rb
display_video? メソッドのテストの網羅度を上げます
https://github.com/cloudnativedaysjp/dreamkast/issues/1022
=> Improve specs for display video

app/controllers/speaker_dashboard/speakers_controller.rb, app/controllers/speaker_dashboards_controller.rb, app/controllers/sponsor_dashboards/speakers_controller.rb, app/controllers/sponsor_dashboards/sponsor_dashboards_controller.rb, app/forms/speaker_form.rb, app/models/talk.rb, app/views/speaker_dashboard/speakers/_talk_fields.html.erb, app/views/speaker_dashboard/speakers/_talk_list.html.erb, app/views/sponsor_dashboards/sponsor_dashboards/_dashboard.html.erb, spec/factories/speakers.rb, spec/factories/talks.rb, spec/requests/speaker_dashboard_spec.rb, spec/requests/sponsor_dashboards/sponsor_dashboards_show_spec.rb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/886
=> Set sponsor id default

db/fixtures/production/privacy_policy_cndt2021.md
fix https://github.com/cloudnativedaysjp/dreamkast/issues/1086
=> add sponsor to privacy policy of cndt2021

db/fixtures/production/01_proposal_item_configs.rb
ALL_OKなどのconstをkeyにして、valueにはテキストをいれる必要がある
fix https://github.com/cloudnativedaysjp/dreamkast/issues/1085
=> seedのkey/valueが逆だった

app/views/speaker_dashboard/speakers/guidance.html.erb
=> fix cfp deadline

app/views/event/o11y2022_show.html.erb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/1102
=> ハイブリッド開催中止の案内を追加

db/fixtures/development/03_sponsors.rb, db/fixtures/production/03_sponsors.rb
https://github.com/cloudnativedaysjp/dreamkast/issues/1104
ロゴはまだないのでtrademarkです
=> add macnica

app/views/admin/timetables/index.html.erb
=> Fix column width

app/views/layouts/_footer.text.erb
=> Change mail footer for o11y2022

app/controllers/application_controller.rb
この件の修正
https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1644243833192169
=> Fix find_by condition to set speaker

app/models/speaker_announcement.rb, app/views/event/o11y2022_show.html.erb
=> Fix event page

app/models/media_package_channel.rb, db/migrate/20220206093040_add_default_value_for_media_package_channels.rb, db/migrate/20220213043022_update_index_of_channel_id_for_media_package_channels.rb, db/schema.rb, spec/models/chat_message_spec.rb
https://github.com/cloudnativedaysjp/dreamkast/pull/1099 でカラムのユニーク制約は消したが、インデックス側を消し忘れていた
=> Fix channel id index

app/models/conference.rb, app/views/event/partial/_information.html.erb, app/views/timetable/_timetable_o11y2022.html.erb, db/fixtures/development/00_seeds.rb, db/fixtures/production/00_seeds.rb, db/migrate/20220213134136_add_committee_name.rb, db/schema.rb, spec/factories/conferences.rb, spec/models/conference_spec.rb, spec/requests/event_spec.rb
https://cloudnativedays.slack.com/archives/C02MECH84MT/p1644744503835499
で指摘があった点を修正。今後も同じ問題が出てくるのでDBで管理するようにした
ついでにタイムテーブルが13時スタートのやつも修正している
=> Make committee name configurable

app/views/profiles/_form.html.erb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/1162
=> 参加登録ボタンの文言に、個人情報保護方針に同意することを追加

app/views/admin/tracks/partial/_talks_table.erb, db/fixtures/development/00_seeds.rb, db/fixtures/production/00_seeds.rb, lib/tasks/add_talks_for_o11y2022_pre_event.rake
fix https://github.com/cloudnativedaysjp/dreamkast/issues/1142
- リリース後、rakeタスクを実行してセッションを登録する
=> update pre event date

lib/tasks/aws.rake, lib/tasks/aws_sqs.rake
review_app で使用したキューが削除されずに残っているため、 review_app のクリーンアップタスクに削除タスクを追加
=> review_app の sqs の自動削除を追加

db/fixtures/development/03_sponsors.rb, db/fixtures/production/03_sponsors.rb
[o11y2022/issues/37](https://github.com/cloudnativedaysjp/o11y2022/issues/37)
の追加要望による修正
=> Change link

app/views/contents/o11y2022_hands_on.html.erb
@MasayaAoyama CICDカンファレンス時の参考にテキスト追加しました。確認お願いします。
=> handson oracle 満員御礼テキスト追加

config/initializers/sentry.rb
=> stop sending performance metrics to sentry

.github/workflows/actionlint.yaml
=> Add action lint

.github/workflows/labeling.yml
action のファイル名は良い名前を募集しています！！！！
---
* `reviewapps/ignore` ラベルを取り除く actions はないので、場合によっては手動で `reviewapps/ignore` ラベルを取り除く必要があります
=> 更新されたファイルによって自動で reviewapps/ignore ラベルを付与するようにした

Gemfile, Gemfile.lock
夢 https://github.com/brianmario/mysql2/releases/tag/0.5.4
=> Update Ruby MySQL lib

.github/workflows/build.yml
ref. https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1652785580611269
=> remove trigger conditions because reviewapp-operator unsupport it

app/views/layouts/_footer.text.erb
=> メールのフッターを cnsec2022 に修正

app/views/timetable/_timetable_cnsec2022.html.erb
=> Add timetable for CNSec2022

app/javascript/stylesheets/cnsec2022/_cnsec2022.scss, app/views/event/cnsec2022_show.html.erb, db/fixtures/development/00_seeds.rb, db/fixtures/production/00_seeds.rb
=> Fix toppage

Gemfile, Gemfile.lock, README.md
=> pre-commitでrubocopを自動で走らせるように

lib/tasks/add_talks_for_cnsec2022_pre_event.rake
https://cloudnativedays.connpass.com/event/252961/
=> Add talks for pre-event

schemas/swagger.yml
=> swaggerの差分を解消

app/javascript/stylesheets/_speaker_dashboard.scss, app/javascript/stylesheets/_tracks.scss, app/views/speaker_dashboard/speakers/_talk_fields.html.erb, app/views/speaker_dashboard/speakers/edit.html.erb, app/views/sponsor_dashboards/speakers/edit.html.erb, app/views/tracks/_speaker_announcements.html.erb, app/views/tracks/waiting.html.erb
Dashboardで気になっていたところを修正
- Dashboardのお知らせのところのタグを間違っていてレイアウトがずれていた
- プロポーザルの概要欄が狭すぎたので広くした
- プロポーザルのプロフィール欄が狭すぎたので広くした
- SCSSっぽく書けていないところを直した
=> Refine dashboard

config/default.conf
=> Fix nginx config for local development

README.md, app/controllers/application_controller.rb, app/controllers/speaker_dashboards_controller.rb, app/controllers/sponsor_dashboards/sponsor_dashboards_controller.rb, app/models/proposal.rb, app/models/video_registration.rb, app/views/speaker_dashboard/speakers/_talk_list.html.erb
Broadcastチームに実際に触って貰って、得られたフィードバックを元に修正
- ドキュメントにパラメータの話が無かったので追加
- 提出状況を日本語表記に
- フォーマットチェックをテーブルとして出力
- controllerにあったhelperをModelに落とした
=> 動画チェック周りをリファクタリング

app/javascript/packs/cropbox.js
記法が違うらしいです
https://github.com/turbolinks/turbolinks#installing-javascript-behavior
=> fix turbolinks loading

app/views/profiles/edit.html.erb
=> Flashメッセージの見た目改善

app/models/conference.rb, app/models/talk.rb, app/models/video_registration.rb, app/views/admin/tracks/partial/_talks_table.erb, db/csv/cnsec2022/proposal_items.csv, db/fixtures/development/00_seeds.rb, db/schema.rb, spec/factories/conferences.rb, spec/factories/proposal_item_configs.rb, spec/factories/proposal_items.rb, spec/factories/video_registrations.rb, spec/models/conference_spec.rb, spec/models/talk_spec.rb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/986
=> Hidden record button non live session

app/javascript/packs/tracks/waiting_channel.js, app/javascript/stylesheets/_tracks.scss, app/views/tracks/waiting.html.erb
Fix #633
ConferenceがOpenになった際に3秒から10秒の間でランダムなカウントダウンを入れてアクセスを散らす
=> Show countdown before move

app/models/profile.rb
=> Fix Profile export

app/helpers/media_live_helper.rb, app/helpers/media_package_helper.rb, app/helpers/ssm_helper.rb, app/models/live_stream_ivs.rb, app/models/live_stream_media_live.rb, app/models/media_package_harvest_job.rb, lib/tasks/aws.rake
fix https://github.com/cloudnativedaysjp/dreamkast/issues/1317
あわせてこちらもマージ・デプロイが必要 https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1802
リリース前にstagingやproductionのMediaLive/MediaPackage/IVSを消すこと
=> use ap-northeast-1 (Tokyo region supports IVS)

app/helpers/job_helper.rb, docker-compose.yaml, localstack/docker-entrypoint-initaws.d/create_queue.sh
fix https://github.com/cloudnativedaysjp/dreamkast/issues/1062
=> use localstack for sqs

.github/workflows/reviewapp.yml
- renovate botのMRをreviewappsの対象外に設定しました
- ブランチ名がrenovate/で始まってそうだったので除外設定しました
- 動作確認はしていないです。。。
=> ignore renovate bot

.github/workflows/gitops-prd.yml, .github/workflows/gitops-stg.yml
github-scriptのバージョンアップにより動かなくなっていたのを直した
=> Fix actions

db/fixtures/development/00_seeds.rb, db/fixtures/production/00_seeds.rb
=> Fix seed for CNDT2022

.rubocop.yml, app/models/talk.rb, spec/models/talk_spec.rb
=> プロポーザルのエクスポートについて修正

app/models/talk.rb, spec/models/talk_spec.rb
fix: https://github.com/cloudnativedaysjp/dreamkast/issues/1539
=> add columns to know sponsor session or not

lib/tasks/modify_session_time_for_keynote_cndt2022.rake
Fix #1554
対象IDは1601, 1603, 1561, 1582
=> Add rake task modify keynote

app/controllers/admin/rooms_controller.rb, app/models/conference.rb, app/models/room.rb, app/models/track.rb, app/views/admin/_navigator.html.erb, app/views/admin/rooms/index.html.erb, app/views/admin/tracks/_tracks_nav.html.erb, config/routes.rb, db/fixtures/development/00_seeds.rb, db/fixtures/production/00_seeds.rb, db/migrate/20221018113936_create_room_table.rb, db/schema.rb, spec/factories/tracks.rb, spec/models/track_spec.rb
管理画面にRoomsページを追加した。ここから各部屋の座席数を変更すると、部屋に紐付くTrack配下のTalkについて座席数を更新する。
=> 各Talkの座席数を設定するためにRoomモデルを追加

db/fixtures/development/00_seeds.rb, db/fixtures/production/00_seeds.rb
=> increase tikets

app/views/contents/o11y.html.erb
=> Fix background

config/default.conf
イベントの度にconfig変更するの手間なので正規表現でuiにプロキシするように変更する。
- /${event}/ui の場合はuiにproxy
- /cableと/_next は前方一致に変更
=> update nginx config

app/models/ticket.rb, app/views/admin/show.html.erb
=> Show ticket status

app/views/talks/partial_show/_col_main_pane.html.erb
=> cndt2021移行はvideojsを使っているので条件分岐を更新する

app/views/api/v1/profiles/my_profile.json.jbuilder, schemas/swagger.yml
dk-ui側で条件判定に使いたく、isAttendOffline fieldをprofile APIに追加しました。
emailもあったほうが良いかと思い、ついでに追加してます。
=> Add email and isAttendOffline attrs on profile api

app/views/contents/cndt2022_hands_on.html.erb
fix https://github.com/cloudnativedaysjp/dreamkast/issues/1603
=> add hands-on by Red Hat

app/models/video_registration.rb
https://cloudnativedays.slack.com/archives/C043FQWNU90/p1667219197070259
の報告への対応
=> video registrationの表示を変更

config/initializers/cors.rb
rack-corsに対する設定ミスでした。
単にワイルドカードにするだけじゃなくて、ガチな正規表現で与えないとダメでした。
手元でOriginヘッダくっつけて試したらいけました。
=> Fix CORS setting

schemas/swagger.yml
dk-fまわりのAPIを更新しました
api gatewayのexport機能でひな型作って、手でコピペしてます。
=> chore: update swagger for dk-functions

app/models/check_in.rb, db/migrate/20221112064311_fix_column_type.rb, db/schema.rb, spec/factories/check_ins.rb, spec/models/check_in_spec.rb, spec/requests/profiles_spec.rb
orderやticketのidがstringであることを気づかずintにしていたので色々死んでいた。
=> チェックイン周りの問題を修正

app/views/api/v1/talks/index.json.jbuilder, schemas/swagger.yml
スタンプラリーの同一スロット内の重複排除のために、slotNum fieldを追加しました
=> feat: Expose slotNum field from talk API

lib/tasks/modify_session_time_for_keynote_cndt2022.rake
https://event.cloudnativedays.jp/cndt2022/talks/1626
のセッション時間を修正
=> Fix talk duration

schemas/swagger.yml
ref: https://github.com/cloudnativedaysjp/dreamkast-functions/pull/57#issuecomment-1315694978
=> chore: update swagger

app/controllers/profiles_controller.rb, app/views/profiles/new.html.erb, spec/requests/profiles_spec.rb
チェックイン時に新規登録していない場合エラーになっていたので修正
=> Fix checkin

app/controllers/talks_controller.rb, app/views/talks/partial_show/_col_main_pane.html.erb, spec/controllers/talks_controller/display_video_spec.rb, spec/models/talk_spec.rb, spec/rails_helper.rb
表示する条件にセッション終了後10分たったかどうかが含まれていない箇所があったので修正。Talk#archived?についてもテストを追加。
=> Fix display video

app/views/talks/partial_show/_talk_video_block_videojs.html.erb
video_idが未入力だと以下の以下のようにソースメディアがないと表示されるため、未入力の場合はアーカイブ作成中である旨を表示する
=> show message if video doesn't video_id

.github/workflows/ci.yml, app/models/chat_message.rb, db/migrate/20221205135248_change_type_of_body_in_chat_message_table.rb, db/schema.rb, spec/models/chat_message_spec.rb
https://github.com/cloudnativedaysjp/dreamkast/issues/1689
=> チャット本文を格納するカラムのデータ型を変更 & Modelに文字数上限のValidationを追加

app/models/conference.rb, app/views/admin/show.html.erb, db/migrate/20221229041946_remove_status_column_from_conference_table.rb, db/schema.rb, spec/factories/conferences.rb, spec/models/conference_spec.rb
https://github.com/cloudnativedaysjp/dreamkast/pull/1721 の続き。statusカラムを削除する。
=> カンファレンスの状態改善その3

app/controllers/admin/conferences_controller.rb, app/forms/conference_form.rb, app/views/admin/conferences/_form.html.erb
https://github.com/cloudnativedaysjp/dreamkast/pull/1740 でshowは直したけどeditは直し漏れていた
=> edit画面の修正漏れ

app/uploaders/avatar_uploader.rb
Shrine(aws sdk) を使用して S3 への画像アップロードを行うと Content-Type が nil で送られてしまうため、アップロード時に File の mime-type を Content-Type に指定するようにした。
Timetable の Permanent link に登壇者画像が出ることは確認しましたが当初の問題となったOGP非表示を解消できているかについては確認できていないです
=> avatar image の upload 時に Content-Type を指定する

app/views/layouts/partial/_login_button.erb
Hotwire導入した影響でログインボタンが動かなくなっていたので修正。ログインボタンではturboを使わないようにする。
=> fix: can't login via auth0

app/helpers/application_helper.rb, app/javascript/packs/vote_cfp.js, app/views/talks/partial_show/_col_main_pane.html.erb
dreamkast function側で破壊的変更を入れた際の修正漏れになります。
=> fix: vote url

app/javascript/packs/application.js, app/javascript/packs/cicd2023.js, app/javascript/packs/cndt2022.js, app/views/layouts/partial/_login_button.erb
Reverts cloudnativedaysjp/dreamkast#1757
=> Revert "fix: can't login via auth0"

app/views/admin/sponsors/_form.html.erb, db/fixtures/development/03_sponsors.rb, db/fixtures/production/03_sponsors.rb
Sponsor typeがないとスポンサー登録できないため追加。
ついでにSponsorの編集でエラーが出ていたので修正
=> Add sponsor type

Dockerfile, Dockerfile.dev
やるぞ！！！！
https://developers.bookwalker.jp/entry/2023/01/25/114710
=> enable YJIT

.github/workflows/build.yml
https://chroju.dev/blog/docker_buildx_slsa_provenance
=> disable provenance

app/controllers/talks_controller.rb
https://github.com/cloudnativedaysjp/dreamkast/issues/1791 の対応
=> fix: registeredの場合、proposalのstatusが考慮されない

app/javascript/packs/application.js, app/javascript/packs/cicd2023.js, app/javascript/packs/cndt2022.js, app/javascript/packs/hotwire.js, app/views/admin/tracks/index.html.erb
Reverts cloudnativedaysjp/dreamkast#1764
=> Revert "fix: enable hotwire partially"

app/models/sponsor_type.rb, app/views/event/partial/_sponsors.html.erb, db/fixtures/development/03_sponsors.rb, db/fixtures/production/03_sponsors.rb, db/migrate/20230208133149_add_visible_flag.rb, db/schema.rb, spec/factories/sponsor_types.rb, spec/models/sponsor_type_spec.rb
表に出したくないスポンサータイプ(リストとか)もあるので、visibleフラグを追加してコントロール出来るようにした(デフォルトはtrue)
=> Toolスポンサー追加とスポンサータイプに非表示フラグの実装

Gemfile.lock, lib/tasks/add_talks_for_cicd2023_pre_event.rake
https://github.com/cloudnativedaysjp/dreamkast/issues/1812
https://cloudnativedays.connpass.com/event/274402/
=> add talks for cicd2023 pre event

app/views/tracks/waiting.html.erb
https://www.notion.so/cloudnativedays/CICD-a5705beba0e14a1fa13eec27867de795
=> CICD2023用のリンクに変更

db/fixtures/production/00_seeds.rb
=> fix: the date of cicd2023 preevent

app/views/admin/tracks/index.html.erb
admin/tracksの画面で新しいものを使うようにしないといけなかったのでそのPRです。毎回追加するの忘れるので条件を逆転させました。
そもそも古い画面は消してもいいと思うけど、ひとまず。
=> use new tracks table

lib/tasks/add_proposal_items_for_cicd2023_rehearsal.rake
stagingでのリハのためにProposalItemがないと録画ができないことに気づいたので追加する。
=> rake: add rake task to add proposal_items for rehearsal

app/views/contents/cicd2023_hands_on.html.erb
３社目のスポンサー様の情報のサイト掲載です。
https://docs.google.com/forms/d/13bzf4Rl4F1Je3T8Pnq5UeKS1TXKy-NWPNFu_QSuPSe8/edit#responses
なお、登録後問い合わせメールにて下記の通りタイトルの変更希望があったため反映しています。
▼変更後タイトル
Jenkins・ArgoCD を利用したCI/CD の実践とコンテナイメージの脆弱性検知
=> CICD2023 Co-locatedハンズオンスポンサー追加

lib/tasks/add_talks_for_cicd2023_intermission.rake
https://github.com/cloudnativedaysjp/dreamkast/issues/1855
=> add rake task to add intermissions for CICD2023

app/controllers/profiles_controller.rb
チェックインと事前登録ボーナスのpoint eventIdを、cicd2023向けに修正しました。
=> fix: Update check-in point eventId to the one for cicd2023

db/fixtures/development/00_seeds.rb, db/fixtures/production/00_seeds.rb
=> Change start time

db/fixtures/development/00_seeds.rb, db/fixtures/production/00_seeds.rb
https://github.com/cloudnativedaysjp/dreamkast/issues/1876
=> add: seed for CNDF2023

.github/renovate.json5
https://github.com/cloudnativedaysjp/dreamkast/issues/1879
=> feat: assign dk-rails team to reviewers of PR by renovate

app/controllers/admin_controller.rb, app/views/admin/statistics.erb, spec/requests/admin/statistics_spec.rb
https://github.com/cloudnativedaysjp/dreamkast/issues/1881
=> feat: チケットに関する数値を表示する

.github/workflows/gitops-prd.yml
ref. https://github.com/marketplace/actions/sentry-release
=> add sentry release

app/controllers/admin/sponsors_controller.rb, app/forms/sponsor_form.rb, app/views/admin/sponsors/_form.html.erb, db/fixtures/development/03_sponsors.rb, db/fixtures/production/03_sponsors.rb
- 入力項目が足りない際に新規登録画面にリダイレクトされる問題を修正
- sponsor_typesを入力してないと無言で新規登録画面にリダイレクトされた
- 更新時にロゴ画像が消える問題を修正
=> Fix admin sponsor form

app/models/conference.rb, app/models/proposal_item_config.rb, app/models/proposal_item_config_check_box.rb, app/models/proposal_item_config_radio_button.rb, app/models/speaker.rb, app/models/talk.rb, app/models/talk_category.rb, app/models/talk_difficulty.rb, app/models/talks_speaker.rb, app/models/track.rb, db/migrate/20230528051104_add_multiple_indexes.rb, db/schema.rb, spec/factories/conferences.rb, spec/factories/proposal_item_configs.rb, spec/factories/speakers.rb, spec/factories/talk_categories.rb, spec/factories/talk_difficulties.rb, spec/factories/talks.rb, spec/factories/tracks.rb, spec/models/conference_spec.rb, spec/models/speaker_spec.rb, spec/models/talk_category_spec.rb, spec/models/talk_difficulty_spec.rb, spec/models/talk_spec.rb, spec/models/track_spec.rb
https://sentry.cloudnativedays.jp/organizations/cloudnative-days/performance/?environment=dreamkast&isDefaultQuery=false&metricSearchSetting=transactionsOnly&sort=-p50 をみて一通りIndexのはれてなさそうな場所にIndexを貼りました
=> Add multiple indexes

Gemfile, Gemfile.lock, config/initializers/sentry.rb
ref. https://docs.sentry.io/platforms/ruby/guides/rails/profiling/
=> add profile on sentry

db/fixtures/development/00_seeds.rb, db/fixtures/production/00_seeds.rb, lib/tasks/add_talks_for_cndf2023_rehearsal_dummy_sessions.rake, lib/tasks/add_talks_for_cndf2023_rehearsal_intermission.rake
https://github.com/cloudnativedaysjp/dreamkast/issues/1950 用のデータを登録するタスクを追加。
=> add dummy sessions and intermissions for rehearsal

app/controllers/attendees_controller.rb, app/models/public_profile.rb, app/views/attendees/index.html.erb, app/views/layouts/_event_header.html.erb, config/routes.rb
`#{abbr}/attendees` ページを追加。
https://github.com/cloudnativedaysjp/dreamkast/issues/1926
=> 参加者一覧ページを追加

app/views/admin/live_stream_ivs/index.html.erb
Broadcastチームの要望によりNotionのIVS設定マニュアルを追加
=> Add link for IVS manual

app/controllers/concerns/talks_table.rb
=> オンエア切り替えのエラー時にエラー色を使う

app/views/layouts/_karte.html.erb
=> Update karte tag

package.json, yarn.lock
=> Update dependency video.js to v8.5.2

.github/workflows/build.yml
image_tag_refを削除してimageのタグはgithub.shaのみとする
=> image_tag_refを削除

app/models/conference.rb, db/migrate/20230909035236_add_streaming_id_columns_to_media_package_tables.rb
productionへのマイグレーションでcollationがずれていてコケるので https://github.com/cloudnativedaysjp/dreamkast/pull/2044 で調整したけど、どうもReviewAppだとうまくいかないようなのでcollationの設定を消す。productionには反映済みなので問題ないだろう。
=> remove collation

app/middlewares/dreamkast_exporter.rb, app/models/proposal_item.rb, app/models/talk.rb
Reverts cloudnativedaysjp/dreamkast#2056
差し戻し
=> Revert "Proposalに関する情報をExporterで出力できるようにする"

app/views/admin/streamings/_default.html.erb
=> 配信用AWSリソース管理画面を改善します

app/models/stats_of_registrant.rb, db/migrate/20231103061142_add_online_and_offline_column_to_stats_of_registrant.rb, db/schema.rb, lib/tasks/post_number_of_registrants_to_slack.rake
=> CNDT2023用の参加者通知を実装

lib/tasks/check_media_live_channel.rake
=> 作成済みのMediaLiveチャンネルをリストアップしてSlack通知する

app/views/contents/cndt2023_hands_on.html.erb
- スリーシェイクさんの時間変更
- 実行委員ハンズオンの参加情報部分の構成変更
=> [cndt2023] ハンズオンページの修正

app/views/contents/cndt2023_hands_on.html.erb
- openshiftさんのロゴへのリンクを変更
- Dynatraceさんの申し込みURLを追加、説明文も変更
=> fix openshift sponsor link & dynatrace detail

app/views/admin/videos/index.html.erb
=> Fix font size

app/models/media_package_v2_origin_endpoint.rb
Reverts cloudnativedaysjp/dreamkast#2149
=> Revert "use original url"

app/views/api/v1/speakers/index.json.jbuilder
オリジナルのファイルが表示されてしまっていたので正方形にクロップされたやつを使うようにする
=> Fix avatar size

app/controllers/admin/check_ins_controller.rb, app/controllers/admin/profiles_controller.rb, app/controllers/admin_controller.rb, app/views/admin/profiles/index.html.erb, config/routes.rb
=> 代理チェックイン機能

app/views/event/show.html.erb
=> Workaround

Gemfile, Gemfile.lock, app/javascript/packs/tracks/track_control.js, app/models/video.rb, app/views/talks/partial_show/_col_sub_pane.html.erb, app/views/tracks/index.html.erb, db/fixtures/development/00_seeds.rb, db/fixtures/production/00_seeds.rb, db/migrate/20240206101323_remove_slido_id_from_video.rb, db/schema.rb, spec/factories/videos.rb, spec/models/video_spec.rb, spec/requests/talks_spec.rb
slidoはもう長い間使っておらず、かつ今後も使わないと思われるので関連コードを削除します。
=> slido関連のコードを削除します

app/controllers/admin/conferences_controller.rb, app/controllers/application_controller.rb, app/forms/conference_form.rb, app/models/conference.rb, app/views/admin/conferences/_form.html.erb, app/views/admin/show.html.erb, app/views/layouts/_event_header.html.erb, db/migrate/20240210070615_add_contact_url_to_conference.rb, db/schema.rb, spec/factories/conferences.rb, spec/models/conference_spec.rb
- お問い合わせURLをDBで管理できるようにしました
- ヘッダのURLまわりに手をいれて少し読みやすくしました
=> Improve header

app/controllers/admin/conferences_controller.rb, app/controllers/application_controller.rb, app/forms/conference_form.rb, app/models/conference.rb, app/views/admin/conferences/_form.html.erb, app/views/admin/show.html.erb, app/views/event/cnds2024_show.html.erb, app/views/event/partial/_sponsor_guideline_link.html.erb, app/views/layouts/_event_header.html.erb, db/migrate/20240114023051_add_type_column_to_talks.rb, db/migrate/20240313151437_add_sponsor_guideline_url_to_c_onference.rb, db/schema.rb, spec/factories/conferences.rb, spec/models/conference_spec.rb
- Conferenceにsponsor_guideline_urlカラムを追加
- トップページとヘッダにリンクを表示できるようにした
https://github.com/cloudnativedaysjp/dreamkast/issues/2228
=> スポンサー募集リンクを表示できるようにする

app/views/event/partial/_sponsor_guideline_link.html.erb
POSTメソッドになってしまってリクエストが失敗するので消す
=> fix: トップページのスポンサー募集リンクに遷移できない問題を修正

app/models/room.rb, db/migrate/20240323074114_remove_integer_from_rooms.rb, db/schema.rb, spec/factories/rooms.rb
See: PR [#1559](https://github.com/cloudnativedaysjp/dreamkast/pull/1559/files#diff-62dd48fb45fb4845f65d90fd91162e09a16be31c6e91ed7724ae896aeb18d28bR8).
=> Remove unintentional `integer` column from `rooms` table

app/controllers/sponsor_dashboards/speakers_controller.rb, app/views/speaker_dashboard/speakers/_speaker_info.html.erb, app/views/speaker_dashboard/speakers/_talk_list.html.erb
https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1712723692302999
=> fix: SponsorDashboardsからセッションを追加できない問題を修正 

app/controllers/admin/live_stream_ivs_controller.rb, app/controllers/concerns/talks_table.rb, app/models/conference.rb, app/models/track.rb
=> Remove associations to deleted LiveStreamMediaLive

config/routes.rb
=> Remove routes for deleted controllers

app/javascript/packs/speaker_form.js
I deploy https://github.com/cloudnativedaysjp/dreamkast/pull/2281 to production, but issue isn't fixed.
I change more fix by https://qiita.com/sho_fcafe/items/192bf0b97b1d84f762ce
=> fix: when document.readyState isn't loading, need to run addEventListener immedeately.

app/controllers/application_controller.rb, app/controllers/concerns/secured.rb, app/controllers/concerns/secured_admin.rb, app/controllers/concerns/secured_api.rb, app/controllers/concerns/secured_speaker.rb, app/controllers/concerns/secured_sponsor.rb, app/helpers/application_helper.rb, spec/controllers/application_controller_spec.rb
Centralizes the definition of the `logged_in?` method by moving it from ApplicationHelper and various controller concerns into ApplicationController.
=> Move `logged_in?` to ApplicationController

app/models/profile.rb
https://cloudnativedays.slack.com/archives/C06PLU48LBW/p1715945544993049?thread_ts=1715944627.003119&cid=C06PLU48LBW
=> User一覧のCSVで参加方法のフラグを出すようにした

app/views/admin/profiles/index.html.erb, app/views/profiles/partial_entry_sheet/_up_left_cell.html.erb
動作確認時にスキャンしやすくしておきます。後、アイコンを登録していないと受付用紙の表示時にエラーになるのでそれも修正しました。
=> adminから各参加者のQRコードを表示できるようにする

app/controllers/admin/speakers_controller.rb, app/views/admin/profiles/index.html.erb, app/views/admin/speakers/speaker_check_in_statues.html.erb
- チェックイン時刻が表示されていなかった
- ついでにチェックイン状況とチェックイン時刻をマージしました
- 登壇者のチェクイン状況ページのテーブルを修正
=> adminのチェックイン機能修正

app/views/attendee_dashboards/show.html.erb, app/views/layouts/partial/_login_button.erb
- https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1718011464913609?thread_ts=1718003262.765189&cid=C015CN1PQ06
- 変更内容はタイトル通り
=> 参加者一人一人に割り当てるものが参加表だと違和感あるので修正

app/controllers/event_controller.rb
registeredとopened以外だとevent_viewが呼ばれないようになっていた
=> イベント終了後はイベントページを描画する

.github/workflows/cron-remove-label.yml
Ref: https://github.com/cloudnativedaysjp/dreamkast-weaver/pull/94
=> fix: SyntaxError

db/fixtures/development/03_sponsors.rb
https://github.com/cloudnativedaysjp/dreamkast/pull/2375 の消し忘れ
=> chore: remove remaining code related to booth

compose-dev.yaml
=> Fix compose-dev

app/controllers/api/v1/chat_messages_controller.rb, schemas/swagger.yml
https://github.com/cloudnativedaysjp/dreamkast-ui/pull/482 用にAPIを更新します
- profile idで絞り込めるようにする
- room idの必須条件を解除する
=> update chat message api

lib/tasks/cleanup_profiles.rake
https://github.com/cloudnativedaysjp/dreamkast/issues/2386
=> fix: cleanup script

app/controllers/stamp_rally_check_ins_controller.rb, app/models/conference.rb, app/models/profile.rb, app/models/stamp_rally_check_in.rb, app/models/stamp_rally_check_point.rb, app/views/admin/stamp_rally_check_points/_stamp_rally_check_point.html.erb, app/views/admin/stamp_rally_check_points/index.html.erb, app/views/stamp_rally_check_ins/index.html.erb, app/views/stamp_rally_check_ins/new.html.erb, config/routes.rb, db/migrate/20241020052204_add_tables_for_stamp_rally_check_ins.rb, db/schema.rb, spec/factories/stamp_rally_check_ins.rb, spec/factories/stamp_rally_check_point_booth.rb, spec/factories/stamp_rally_check_point_finish.rb, spec/requests/stamp_rally_check_ins_spec.rb
Implement https://www.notion.so/pfem/34dbdb151f134b07808f27add4a7a1dc?pvs=4#75670af18a3b442bb53dd2a4ab009579
=> feat: implement check in for stamp rally

app/views/attendee_dashboards/show.html.erb, app/views/contents/cndw2024/_projects.html.erb
- OSS企画のリンク先変更
- OSS企画のリンクとバナーがダブっていたので削除
=> Change link address

app/jobs/generate_entrysheet_job.rb, compose.yaml
https://github.com/rubycdp/ferrum/issues/289
=> fix: Ferrum::ProcessTimeoutError

.github/workflows/push-tag-by-releasebot.yml
ref. https://github.com/cloudnativedaysjp/dreamkast/actions/runs/14529668946
=> fix permissions

app/views/event/cnds2025_show.html.erb, app/views/timetable/_timetable_cnds2025.erb, lib/tasks/add_talks_for_cnds2025_intermission.rake
いつものようにIntermissionの追加と、実行委員の要請でComing soonなセッションを追加
ついでにタイムテーブルのズレを修正
=> Add intermission and tbd session

app/views/event/cnds2025_show.html.erb, app/views/timetable/_timetable_cnds2025.erb, db/fixtures/development/00_seeds.rb, db/fixtures/production/00_seeds.rb
この修正要望への対応
https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1745393175348189
=> Fix timetable
